-- Create "custom_config_resources" table
CREATE TABLE "custom_config_resources" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "resource_id" character varying NOT NULL, "name" character varying NOT NULL, "description" character varying NULL, "config_data" character varying NOT NULL, "tenant_id" character varying NOT NULL, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL, PRIMARY KEY ("id"));
-- Create index "custom_config_resources_resource_id_key" to table: "custom_config_resources"
CREATE UNIQUE INDEX "custom_config_resources_resource_id_key" ON "custom_config_resources" ("resource_id");
-- Create index "customconfigresource_name_tenant_id" to table: "custom_config_resources"
CREATE UNIQUE INDEX "customconfigresource_name_tenant_id" ON "custom_config_resources" ("name", "tenant_id");
-- Create index "customconfigresource_tenant_id" to table: "custom_config_resources"
CREATE INDEX "customconfigresource_tenant_id" ON "custom_config_resources" ("tenant_id");
-- Modify "instance_resources" table
ALTER TABLE "instance_resources" ADD COLUMN "instance_resource_custom_config" bigint NULL, ADD CONSTRAINT "instance_resources_custom_config_resources_custom_config" FOREIGN KEY ("instance_resource_custom_config") REFERENCES "custom_config_resources" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
