# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

CI 🤖:
  - changed-files:
      - any-glob-to-any-file: ".github/**"

root:
  - changed-files:
      - any-glob-to-any-file: "*"

api:
  - changed-files:
    - any-glob-to-any-file: "api/**"

apiv2:
  - changed-files:
      - any-glob-to-any-file: "apiv2/**"

bulk-import-tools:
  - changed-files:
    - any-glob-to-any-file: "bulk-import-tools/**"

exporters-inventory:
  - changed-files:
    - any-glob-to-any-file: "exporters-inventory/**"

inventory:
  - changed-files:
    - any-glob-to-any-file: "inventory/**"

tenant-controller:
  - changed-files:
    - any-glob-to-any-file: "tenant-controller/**"

os-profiles:
  - changed-files:
      - any-glob-to-any-file: "os-profiles/**"
