# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
version: "2"
run:
  go: ""
  modules-download-mode: readonly
  issues-exit-code: 1
  tests: true
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
    html:
      path: out/golangci-lint_report.html
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - cyclop
    - depguard
    - dogsled
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goheader
    - gomoddirectives
    - goprintffuncname
    - gosec
    - lll
    - misspell
    - mnd
    - nakedret
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - tagliatelle
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - whitespace
  settings:
    cyclop:
      max-complexity: 10
    depguard:
      rules:
        Main:
          files:
            - $all
            - '!$test'
          allow:
            - $gostd
            - github.com/open-edge-platform
            - entgo.io/ent
            - entgo.io/contrib/entproto
            - entgo.io/contrib/entproto/cmd/protoc-gen-ent/options/ent
            - entgo.io/contrib/schemas
            - github.com/goccy/go-json
            - github.com/golang/mock/gomock
            - github.com/google
            - github.com/grpc-ecosystem
            - github.com/mennanov/fmutils
            - github.com/labstack/echo
            - github.com/open-policy-agent
            - github.com/pkg/errors
            - github.com/rs/zerolog
            - github.com/cenkalti/backoff
            - github.com/stretchr/testify/require
            - github.com/iancoleman/strcase
            - github.com/jackc/pgx/v5/stdlib
            - github.com/hashicorp/vault/api
            - github.com/golang-jwt/jwt/v5
            - buf.build/go/protovalidate
            - github.com/adhocore/gronx
            - github.com/prometheus/client_golang/prometheus
            - github.com/lib/pq
            - github.com/mitchellh/mapstructure
            - github.com/Nerzal/gocloak
            - oras.land/oras-go/v2
            - github.com/opencontainers/image-spec
            - github.com/patrickmn/go-cache
            - github.com/eko/gocache/store/go_cache/v4
            - github.com/eko/gocache/lib/v4/cache
            - github.com/eko/gocache/lib/v4/store
            - github.com/golang/mock/mockgen/model
        Test:
          files:
            - $test
          allow:
            - $gostd
            - github.com/open-edge-platform
            - github.com/goccy/go-json
            - github.com/golang/mock/gomock
            - github.com/google
            - github.com/grpc-ecosystem
            - github.com/mennanov/fmutils
            - github.com/rs/zerolog
            - github.com/stretchr/testify/require
            - github.com/stretchr/testify/assert
            - github.com/stretchr/testify/suite
            - github.com/grpc-ecosystem/go-grpc-middleware/util/metautils
            - github.com/hashicorp/vault/api
            - buf.build/go/protovalidate
            - github.com/labstack/echo/v4
            - github.com/golang-jwt/jwt/v5
            - github.com/Nerzal/gocloak
            - entgo.io/ent/dialect/sql
            - github.com/prometheus/client_golang/prometheus
          deny:
            - pkg: github.com/stretchr/testify/mock
              desc: mocking with testify is prohibited, please use gomock
    errcheck:
      check-type-assertions: true
      check-blank: true
      exclude-functions:
        - io/ioutil.ReadFile
        - io.Copy(*bytes.Buffer)
        - io.Copy(os.Stdout)
    exhaustive:
      default-signifies-exhaustive: true
    funlen:
      lines: 100
      statements: 50
    gocritic:
      disabled-checks:
        - hugeParam
        - rangeExprCopy
        - rangeValCopy
        - unnamedResult
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    govet:
      enable:
        - shadow
    lll:
      line-length: 130
      tab-width: 4
    misspell:
      locale: US
    nakedret:
      max-func-lines: 1
    tagliatelle:
      case:
        rules:
          avro: snake
          bson: camel
          json: snake
          mapstructure: kebab
          xml: camel
          yaml: snake
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - cyclop
          - funlen
        path: internal/inventory/inventory.go
      - linters:
          - cyclop
        path: internal/policy/policy.go
      - linters:
          - funlen
        path: internal/policy/policy_test.go
      - linters:
          - errcheck
          - funlen
        path: internal/store/endpoint_test.go
      - linters:
          - cyclop
          - funlen
        path: internal/store/host_test.go
      - linters:
          - cyclop
          - errcheck
          - funlen
        path: internal/store/hostnic_test.go
      - linters:
          - cyclop
          - errcheck
          - funlen
        path: internal/store/hoststorage_test.go
      - linters:
          - cyclop
          - errcheck
          - funlen
        path: internal/store/hostusb_test.go
      - linters:
          - cyclop
          - errcheck
          - funlen
        path: internal/store/hostgpu_test.go
      - linters:
          - cyclop
          - funlen
        path: internal/store/ip_address_test.go
      - linters:
          - cyclop
          - errcheck
          - funlen
        path: internal/store/netlink_test.go
      - linters:
          - cyclop
          - errcheck
          - funlen
        path: internal/store/networksegment_test.go
      - linters:
          - cyclop
          - errcheck
          - funlen
        path: internal/store/os_test.go
      - linters:
          - cyclop
          - errcheck
          - funlen
        path: internal/store/ou_test.go
      - linters:
          - cyclop
          - errcheck
          - funlen
        path: internal/store/project_test.go
      - linters:
          - cyclop
          - errcheck
          - funlen
        path: internal/store/provider_test.go
      - linters:
          - cyclop
          - funlen
        path: internal/store/region_test.go
      - linters:
          - cyclop
          - errcheck
          - funlen
        path: internal/store/repeatedschedule_test.go
      - linters:
          - cyclop
          - errcheck
          - funlen
        path: internal/store/singleschedule_test.go
      - linters:
          - cyclop
          - errcheck
          - funlen
        path: internal/store/site_test.go
      - linters:
          - lll
        path: internal/store/store_test.go
      - linters:
          - cyclop
          - funlen
        path: internal/store/workload_test.go
      - linters:
          - cyclop
          - funlen
        path: internal/store/workload_member_test.go
      - linters:
          - cyclop
        path: internal/store/store.go
      - linters:
          - cyclop
          - errcheck
          - funlen
        path: internal/store/user_test.go
      - linters:
          - cyclop
          - errcheck
          - funlen
        path: internal/store/instance_test.go
      - linters:
          - cyclop
          - errcheck
          - funlen
          - gosec
        path: internal/store/remoteaccess_test.go
      - linters:
          - cyclop
          - errcheck
          - funlen
        path: internal/store/telemetryprofile_test.go
      - linters:
          - cyclop
          - errcheck
          - funlen
        path: internal/store/telemetrygroup_test.go
      - linters:
          - gosec
        path: pkg/cert/cert.go
      - linters:
          - cyclop
          - funlen
          - gocyclo
        path: pkg/errors/errors.go
      - linters:
          - cyclop
          - errcheck
          - funlen
          - testableexamples
        path: pkg/errors/errors_test.go
      - linters:
          - cyclop
        path: pkg/policy/policy.go
      - linters:
          - funlen
        path: pkg/policy/policy_test.go
      - linters:
          - cyclop
        path: pkg/policy/rbac/rbac.go
      - linters:
          - funlen
          - gocritic
        path: pkg/policy/rbac/rbac_test.go
      - linters:
          - mnd
        path: pkg/testing/testing_utils.go
      - linters:
          - mnd
        path: pkg/testing/generators.go
      - linters:
          - gosec
        path: pkg/perf/perf.go
      - linters:
          - funlen
          - gosec
        path: pkg/fuzz/client_fuzz_test.go
      - path: (.+)\.go$
        text: Error return value of `.*Close` is not checked
      - path: (.+)\.go$
        text: Error return value of `.*Flush` is not checked
      - path: (.+)\.go$
        text: Error return value of `.*Write` is not checked
      - path: (.+)\.go$
        text: Error return value of `.*Stop` is not checked
    paths:
      - pkg/api/
      - internal/ent
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: false
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/open-edge-platform)
  exclusions:
    generated: lax
    paths:
      - pkg/api/
      - internal/ent
      - third_party$
      - builtin$
      - examples$
      - internal/ent/.*
