// SPDX-FileCopyrightText: (C) 2026 Intel Corporation
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: resources/common/v1/common.proto

package commonv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A label item for small key-value pairs used for selection and filtering.
type LabelItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The label key.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// The label value.
	Value         string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabelItem) Reset() {
	*x = LabelItem{}
	mi := &file_resources_common_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabelItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelItem) ProtoMessage() {}

func (x *LabelItem) ProtoReflect() protoreflect.Message {
	mi := &file_resources_common_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelItem.ProtoReflect.Descriptor instead.
func (*LabelItem) Descriptor() ([]byte, []int) {
	return file_resources_common_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *LabelItem) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LabelItem) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// An annotation item for larger configuration data.
type AnnotationItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The annotation key.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// The annotation value.
	Value         string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnotationItem) Reset() {
	*x = AnnotationItem{}
	mi := &file_resources_common_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnotationItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnotationItem) ProtoMessage() {}

func (x *AnnotationItem) ProtoReflect() protoreflect.Message {
	mi := &file_resources_common_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnotationItem.ProtoReflect.Descriptor instead.
func (*AnnotationItem) Descriptor() ([]byte, []int) {
	return file_resources_common_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *AnnotationItem) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AnnotationItem) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// A metadata item, represented by either a label or annotation.
type MetadataItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Item:
	//
	//	*MetadataItem_Label
	//	*MetadataItem_Annotation
	Item          isMetadataItem_Item `protobuf_oneof:"item"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataItem) Reset() {
	*x = MetadataItem{}
	mi := &file_resources_common_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataItem) ProtoMessage() {}

func (x *MetadataItem) ProtoReflect() protoreflect.Message {
	mi := &file_resources_common_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataItem.ProtoReflect.Descriptor instead.
func (*MetadataItem) Descriptor() ([]byte, []int) {
	return file_resources_common_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *MetadataItem) GetItem() isMetadataItem_Item {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *MetadataItem) GetLabel() *LabelItem {
	if x != nil {
		if x, ok := x.Item.(*MetadataItem_Label); ok {
			return x.Label
		}
	}
	return nil
}

func (x *MetadataItem) GetAnnotation() *AnnotationItem {
	if x != nil {
		if x, ok := x.Item.(*MetadataItem_Annotation); ok {
			return x.Annotation
		}
	}
	return nil
}

type isMetadataItem_Item interface {
	isMetadataItem_Item()
}

type MetadataItem_Label struct {
	// A label for small key-value pairs used for selection and filtering.
	Label *LabelItem `protobuf:"bytes,1,opt,name=label,proto3,oneof"`
}

type MetadataItem_Annotation struct {
	// An annotation for larger configuration data like kubeconfig.
	Annotation *AnnotationItem `protobuf:"bytes,2,opt,name=annotation,proto3,oneof"`
}

func (*MetadataItem_Label) isMetadataItem_Item() {}

func (*MetadataItem_Annotation) isMetadataItem_Item() {}

type Timestamps struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The time when the resource was created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// The time when the resource was last updated.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timestamps) Reset() {
	*x = Timestamps{}
	mi := &file_resources_common_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timestamps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timestamps) ProtoMessage() {}

func (x *Timestamps) ProtoReflect() protoreflect.Message {
	mi := &file_resources_common_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timestamps.ProtoReflect.Descriptor instead.
func (*Timestamps) Descriptor() ([]byte, []int) {
	return file_resources_common_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *Timestamps) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Timestamps) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_resources_common_v1_common_proto protoreflect.FileDescriptor

const file_resources_common_v1_common_proto_rawDesc = "" +
	"\n" +
	" resources/common/v1/common.proto\x12\x13resources.common.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bbuf/validate/validate.proto\"\xef\x01\n" +
	"\tLabelItem\x12\x8f\x01\n" +
	"\x03key\x18\x01 \x01(\tB}\xe0A\x02\xbaHwru\x10\x00\x18\xbc\x022n^$|^[a-z.]+/$|^[a-z.]+/[a-z0-9][a-z0-9-_.]*[a-z0-9]$|^[a-z.]+/[a-z0-9]$|^[a-z]$|^[a-z0-9][a-z0-9-_.]*[a-z0-9]$R\x03key\x12P\n" +
	"\x05value\x18\x02 \x01(\tB:\xe0A\x02\xbaH4r2\x10\x00\x18?2,^$|^[a-z0-9]$|^[a-z0-9][a-z0-9._-]*[a-z0-9]$R\x05value\"\xc7\x01\n" +
	"\x0eAnnotationItem\x12\x8f\x01\n" +
	"\x03key\x18\x01 \x01(\tB}\xe0A\x02\xbaHwru\x10\x00\x18\xbc\x022n^$|^[a-z.]+/$|^[a-z.]+/[a-z0-9][a-z0-9-_.]*[a-z0-9]$|^[a-z.]+/[a-z0-9]$|^[a-z]$|^[a-z0-9][a-z0-9-_.]*[a-z0-9]$R\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\tB\r\xe0A\x02\xbaH\ar\x05\x10\x00\x18\x80 R\x05value\"\x95\x01\n" +
	"\fMetadataItem\x126\n" +
	"\x05label\x18\x01 \x01(\v2\x1e.resources.common.v1.LabelItemH\x00R\x05label\x12E\n" +
	"\n" +
	"annotation\x18\x02 \x01(\v2#.resources.common.v1.AnnotationItemH\x00R\n" +
	"annotationB\x06\n" +
	"\x04item\"\x8c\x01\n" +
	"\n" +
	"Timestamps\x12>\n" +
	"\n" +
	"created_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\tcreatedAt\x12>\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\tupdatedAtB_Z]github.com/open-edge-platform/infra-core/apiv2/v2/internal/pbapi/resources/common/v1;commonv1b\x06proto3"

var (
	file_resources_common_v1_common_proto_rawDescOnce sync.Once
	file_resources_common_v1_common_proto_rawDescData []byte
)

func file_resources_common_v1_common_proto_rawDescGZIP() []byte {
	file_resources_common_v1_common_proto_rawDescOnce.Do(func() {
		file_resources_common_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resources_common_v1_common_proto_rawDesc), len(file_resources_common_v1_common_proto_rawDesc)))
	})
	return file_resources_common_v1_common_proto_rawDescData
}

var file_resources_common_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_resources_common_v1_common_proto_goTypes = []any{
	(*LabelItem)(nil),             // 0: resources.common.v1.LabelItem
	(*AnnotationItem)(nil),        // 1: resources.common.v1.AnnotationItem
	(*MetadataItem)(nil),          // 2: resources.common.v1.MetadataItem
	(*Timestamps)(nil),            // 3: resources.common.v1.Timestamps
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_resources_common_v1_common_proto_depIdxs = []int32{
	0, // 0: resources.common.v1.MetadataItem.label:type_name -> resources.common.v1.LabelItem
	1, // 1: resources.common.v1.MetadataItem.annotation:type_name -> resources.common.v1.AnnotationItem
	4, // 2: resources.common.v1.Timestamps.created_at:type_name -> google.protobuf.Timestamp
	4, // 3: resources.common.v1.Timestamps.updated_at:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_resources_common_v1_common_proto_init() }
func file_resources_common_v1_common_proto_init() {
	if File_resources_common_v1_common_proto != nil {
		return
	}
	file_resources_common_v1_common_proto_msgTypes[2].OneofWrappers = []any{
		(*MetadataItem_Label)(nil),
		(*MetadataItem_Annotation)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resources_common_v1_common_proto_rawDesc), len(file_resources_common_v1_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_resources_common_v1_common_proto_goTypes,
		DependencyIndexes: file_resources_common_v1_common_proto_depIdxs,
		MessageInfos:      file_resources_common_v1_common_proto_msgTypes,
	}.Build()
	File_resources_common_v1_common_proto = out.File
	file_resources_common_v1_common_proto_goTypes = nil
	file_resources_common_v1_common_proto_depIdxs = nil
}
