// Code generated by protoc-gen-go-const. DO NOT EDIT.

// source: resources/schedule/v1/schedule.proto

package schedulev1

const (
	// Fields and Edges constants for "SingleScheduleResource"
	SingleScheduleResourceFieldResourceId       = "resource_id"
	SingleScheduleResourceFieldScheduleStatus   = "schedule_status"
	SingleScheduleResourceFieldName             = "name"
	SingleScheduleResourceEdgeTargetSite        = "target_site"
	SingleScheduleResourceEdgeTargetHost        = "target_host"
	SingleScheduleResourceEdgeTargetRegion      = "target_region"
	SingleScheduleResourceFieldStartSeconds     = "start_seconds"
	SingleScheduleResourceFieldEndSeconds       = "end_seconds"
	SingleScheduleResourceFieldSingleScheduleId = "single_schedule_id"
	SingleScheduleResourceFieldTargetHostId     = "target_host_id"
	SingleScheduleResourceFieldTargetSiteId     = "target_site_id"
	SingleScheduleResourceFieldTargetRegionId   = "target_region_id"
	SingleScheduleResourceEdgeTimestamps        = "timestamps"

	// Fields and Edges constants for "RepeatedScheduleResource"
	RepeatedScheduleResourceFieldResourceId         = "resource_id"
	RepeatedScheduleResourceFieldScheduleStatus     = "schedule_status"
	RepeatedScheduleResourceFieldName               = "name"
	RepeatedScheduleResourceEdgeTargetSite          = "target_site"
	RepeatedScheduleResourceEdgeTargetHost          = "target_host"
	RepeatedScheduleResourceEdgeTargetRegion        = "target_region"
	RepeatedScheduleResourceFieldDurationSeconds    = "duration_seconds"
	RepeatedScheduleResourceFieldCronMinutes        = "cron_minutes"
	RepeatedScheduleResourceFieldCronHours          = "cron_hours"
	RepeatedScheduleResourceFieldCronDayMonth       = "cron_day_month"
	RepeatedScheduleResourceFieldCronMonth          = "cron_month"
	RepeatedScheduleResourceFieldCronDayWeek        = "cron_day_week"
	RepeatedScheduleResourceFieldRepeatedScheduleId = "repeated_schedule_id"
	RepeatedScheduleResourceFieldTargetHostId       = "target_host_id"
	RepeatedScheduleResourceFieldTargetSiteId       = "target_site_id"
	RepeatedScheduleResourceFieldTargetRegionId     = "target_region_id"
	RepeatedScheduleResourceEdgeTimestamps          = "timestamps"
)
