// SPDX-FileCopyrightText: (C) 2025 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-filters, DO NOT EDIT.

package store

import (
	"github.com/open-edge-platform/infra-core/inventory/v2/internal/ent/hostamtconfigresource"
	inv_v1 "github.com/open-edge-platform/infra-core/inventory/v2/pkg/api/inventory/v1"
)

func (r *registry) RegisterHostamtconfigResource() {
	r.Register(
		newResourceTranspiler(
			inv_v1.ResourceKind_RESOURCE_KIND_HOSTAMTCONFIG,
			hostamtconfigresource.ValidColumn,
			map[string]edgeHandler{
				hostamtconfigresource.EdgeHost: {
					func(p sqlPredicate) sqlPredicate { return hostamtconfigresource.HasHostWith(p) },
					inv_v1.ResourceKind_RESOURCE_KIND_HOST,
				},
			},
			map[string]sqlPredicate{
				hostamtconfigresource.EdgeHost: hostamtconfigresource.HasHost(),
			},
		))

}
