// SPDX-FileCopyrightText: (C) 2025 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-filters, DO NOT EDIT.

package store

import (
	"github.com/open-edge-platform/infra-core/inventory/v2/internal/ent/osupdatepolicyresource"
	inv_v1 "github.com/open-edge-platform/infra-core/inventory/v2/pkg/api/inventory/v1"
)

func (r *registry) RegisterOsupdatePolicyResource() {
	r.Register(
		newResourceTranspiler(
			inv_v1.ResourceKind_RESOURCE_KIND_OSUPDATEPOLICY,
			osupdatepolicyresource.ValidColumn,
			map[string]edgeHandler{
				osupdatepolicyresource.EdgeTargetOs: {
					func(p sqlPredicate) sqlPredicate { return osupdatepolicyresource.HasTargetOsWith(p) },
					inv_v1.ResourceKind_RESOURCE_KIND_OS,
				},
			},
			map[string]sqlPredicate{
				osupdatepolicyresource.EdgeTargetOs: osupdatepolicyresource.HasTargetOs(),
			},
		))

}
