// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: resources/localaccount/v1/localaccount.proto

package localaccountv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on LocalAccountResource with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *LocalAccountResource) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LocalAccountResource with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// LocalAccountResourceMultiError, or nil if none found.
func (m *LocalAccountResource) ValidateAll() error {
	return m.validate(true)
}

func (m *LocalAccountResource) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetResourceId()) > 21 {
		err := LocalAccountResourceValidationError{
			field:  "ResourceId",
			reason: "value length must be at most 21 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_LocalAccountResource_ResourceId_Pattern.MatchString(m.GetResourceId()) {
		err := LocalAccountResourceValidationError{
			field:  "ResourceId",
			reason: "value does not match regex pattern \"^localaccount-[0-9a-f]{8}$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetUsername()) > 32 {
		err := LocalAccountResourceValidationError{
			field:  "Username",
			reason: "value length must be at most 32 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_LocalAccountResource_Username_Pattern.MatchString(m.GetUsername()) {
		err := LocalAccountResourceValidationError{
			field:  "Username",
			reason: "value does not match regex pattern \"^[a-z][a-z0-9-]{0,31}$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetSshKey()) > 800 {
		err := LocalAccountResourceValidationError{
			field:  "SshKey",
			reason: "value length must be at most 800 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_LocalAccountResource_SshKey_Pattern.MatchString(m.GetSshKey()) {
		err := LocalAccountResourceValidationError{
			field:  "SshKey",
			reason: "value does not match regex pattern \"^(ssh-ed25519|ecdsa-sha2-nistp521) ([A-Za-z0-9+/=]+) ?(.*)?$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetLocalAccountID()) > 21 {
		err := LocalAccountResourceValidationError{
			field:  "LocalAccountID",
			reason: "value length must be at most 21 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_LocalAccountResource_LocalAccountID_Pattern.MatchString(m.GetLocalAccountID()) {
		err := LocalAccountResourceValidationError{
			field:  "LocalAccountID",
			reason: "value does not match regex pattern \"^localaccount-[0-9a-f]{8}$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetTimestamps()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, LocalAccountResourceValidationError{
					field:  "Timestamps",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, LocalAccountResourceValidationError{
					field:  "Timestamps",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTimestamps()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return LocalAccountResourceValidationError{
				field:  "Timestamps",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return LocalAccountResourceMultiError(errors)
	}

	return nil
}

// LocalAccountResourceMultiError is an error wrapping multiple validation
// errors returned by LocalAccountResource.ValidateAll() if the designated
// constraints aren't met.
type LocalAccountResourceMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LocalAccountResourceMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LocalAccountResourceMultiError) AllErrors() []error { return m }

// LocalAccountResourceValidationError is the validation error returned by
// LocalAccountResource.Validate if the designated constraints aren't met.
type LocalAccountResourceValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LocalAccountResourceValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LocalAccountResourceValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LocalAccountResourceValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LocalAccountResourceValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LocalAccountResourceValidationError) ErrorName() string {
	return "LocalAccountResourceValidationError"
}

// Error satisfies the builtin error interface
func (e LocalAccountResourceValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLocalAccountResource.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LocalAccountResourceValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LocalAccountResourceValidationError{}

var _LocalAccountResource_ResourceId_Pattern = regexp.MustCompile("^localaccount-[0-9a-f]{8}$")

var _LocalAccountResource_Username_Pattern = regexp.MustCompile("^[a-z][a-z0-9-]{0,31}$")

var _LocalAccountResource_SshKey_Pattern = regexp.MustCompile("^(ssh-ed25519|ecdsa-sha2-nistp521) ([A-Za-z0-9+/=]+) ?(.*)?$")

var _LocalAccountResource_LocalAccountID_Pattern = regexp.MustCompile("^localaccount-[0-9a-f]{8}$")
