// Code generated by protoc-gen-go-const. DO NOT EDIT.

// source: services/v1/services.proto

package servicesv1

const (
	// Fields and Edges constants for "CreateRegionRequest"
	CreateRegionRequestEdgeRegion       = "region"
	CreateRegionRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "CreateRegionResponse"
	CreateRegionResponseEdgeRegion = "region"

	// Fields and Edges constants for "GetRegionRequest"
	GetRegionRequestFieldResourceId  = "resourceId"
	GetRegionRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "GetRegionResponse"
	GetRegionResponseEdgeRegion = "region"

	// Fields and Edges constants for "ListRegionsRequest"
	ListRegionsRequestFieldOrderBy        = "order_by"
	ListRegionsRequestFieldFilter         = "filter"
	ListRegionsRequestFieldPageSize       = "page_size"
	ListRegionsRequestFieldOffset         = "offset"
	ListRegionsRequestFieldShowTotalSites = "show_total_sites"
	ListRegionsRequestFieldProjectName    = "projectName"

	// Fields and Edges constants for "ListRegionsResponse"
	ListRegionsResponseEdgeRegions        = "regions"
	ListRegionsResponseFieldTotalElements = "total_elements"
	ListRegionsResponseFieldHasNext       = "has_next"

	// Fields and Edges constants for "UpdateRegionRequest"
	UpdateRegionRequestFieldResourceId  = "resourceId"
	UpdateRegionRequestEdgeRegion       = "region"
	UpdateRegionRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "PatchRegionRequest"
	PatchRegionRequestFieldResourceId  = "resourceId"
	PatchRegionRequestEdgeRegion       = "region"
	PatchRegionRequestEdgeFieldMask    = "field_mask"
	PatchRegionRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "DeleteRegionRequest"
	DeleteRegionRequestFieldResourceId  = "resourceId"
	DeleteRegionRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "DeleteRegionResponse"

	// Fields and Edges constants for "CreateSiteRequest"
	CreateSiteRequestEdgeSite         = "site"
	CreateSiteRequestFieldProjectName = "projectName"
	CreateSiteRequestFieldRegionId    = "regionId"

	// Fields and Edges constants for "CreateSiteResponse"
	CreateSiteResponseEdgeSite = "site"

	// Fields and Edges constants for "GetSiteRequest"
	GetSiteRequestFieldResourceId  = "resourceId"
	GetSiteRequestFieldProjectName = "projectName"
	GetSiteRequestFieldRegionId    = "regionId"

	// Fields and Edges constants for "GetSiteResponse"
	GetSiteResponseEdgeSite = "site"

	// Fields and Edges constants for "ListSitesRequest"
	ListSitesRequestFieldOrderBy     = "order_by"
	ListSitesRequestFieldFilter      = "filter"
	ListSitesRequestFieldPageSize    = "page_size"
	ListSitesRequestFieldOffset      = "offset"
	ListSitesRequestFieldProjectName = "projectName"
	ListSitesRequestFieldRegionId    = "regionId"

	// Fields and Edges constants for "ListSitesResponse"
	ListSitesResponseEdgeSites          = "sites"
	ListSitesResponseFieldTotalElements = "total_elements"
	ListSitesResponseFieldHasNext       = "has_next"

	// Fields and Edges constants for "UpdateSiteRequest"
	UpdateSiteRequestFieldResourceId  = "resourceId"
	UpdateSiteRequestEdgeSite         = "site"
	UpdateSiteRequestFieldProjectName = "projectName"
	UpdateSiteRequestFieldRegionId    = "regionId"

	// Fields and Edges constants for "PatchSiteRequest"
	PatchSiteRequestFieldResourceId  = "resourceId"
	PatchSiteRequestEdgeSite         = "site"
	PatchSiteRequestEdgeFieldMask    = "field_mask"
	PatchSiteRequestFieldRegionId    = "regionId"
	PatchSiteRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "DeleteSiteRequest"
	DeleteSiteRequestFieldResourceId  = "resourceId"
	DeleteSiteRequestFieldProjectName = "projectName"
	DeleteSiteRequestFieldRegionId    = "regionId"

	// Fields and Edges constants for "DeleteSiteResponse"

	// Fields and Edges constants for "ListLocationsRequest"
	ListLocationsRequestFieldName        = "name"
	ListLocationsRequestFieldShowSites   = "show_sites"
	ListLocationsRequestFieldShowRegions = "show_regions"
	ListLocationsRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "ListLocationsResponse"
	ListLocationsResponseEdgeNodes           = "nodes"
	ListLocationsResponseFieldTotalElements  = "total_elements"
	ListLocationsResponseFieldOutputElements = "output_elements"

	// Fields and Edges constants for "GetHostSummaryRequest"
	GetHostSummaryRequestFieldFilter      = "filter"
	GetHostSummaryRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "GetHostSummaryResponse"
	GetHostSummaryResponseFieldTotal       = "total"
	GetHostSummaryResponseFieldError       = "error"
	GetHostSummaryResponseFieldRunning     = "running"
	GetHostSummaryResponseFieldUnallocated = "unallocated"

	// Fields and Edges constants for "CreateHostRequest"
	CreateHostRequestEdgeHost         = "host"
	CreateHostRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "CreateHostResponse"
	CreateHostResponseEdgeHost = "host"

	// Fields and Edges constants for "GetHostRequest"
	GetHostRequestFieldResourceId  = "resourceId"
	GetHostRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "GetHostResponse"
	GetHostResponseEdgeHost = "host"

	// Fields and Edges constants for "ListHostsRequest"
	ListHostsRequestFieldOrderBy     = "order_by"
	ListHostsRequestFieldFilter      = "filter"
	ListHostsRequestFieldPageSize    = "page_size"
	ListHostsRequestFieldOffset      = "offset"
	ListHostsRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "ListHostsResponse"
	ListHostsResponseEdgeHosts          = "hosts"
	ListHostsResponseFieldTotalElements = "total_elements"
	ListHostsResponseFieldHasNext       = "has_next"

	// Fields and Edges constants for "UpdateHostRequest"
	UpdateHostRequestFieldResourceId  = "resourceId"
	UpdateHostRequestEdgeHost         = "host"
	UpdateHostRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "PatchHostRequest"
	PatchHostRequestFieldResourceId  = "resourceId"
	PatchHostRequestEdgeHost         = "host"
	PatchHostRequestEdgeFieldMask    = "field_mask"
	PatchHostRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "DeleteHostRequest"
	DeleteHostRequestFieldResourceId  = "resourceId"
	DeleteHostRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "DeleteHostResponse"

	// Fields and Edges constants for "InvalidateHostRequest"
	InvalidateHostRequestFieldResourceId  = "resourceId"
	InvalidateHostRequestFieldNote        = "note"
	InvalidateHostRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "InvalidateHostResponse"

	// Fields and Edges constants for "HostRegister"
	HostRegisterFieldName         = "name"
	HostRegisterFieldSerialNumber = "serial_number"
	HostRegisterFieldUuid         = "uuid"
	HostRegisterFieldAutoOnboard  = "auto_onboard"
	HostRegisterFieldEnableVpro   = "enable_vpro"
	HostRegisterFieldUserLvmSize  = "user_lvm_size"

	// Fields and Edges constants for "RegisterHostRequest"
	RegisterHostRequestFieldResourceId  = "resourceId"
	RegisterHostRequestEdgeHost         = "host"
	RegisterHostRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "OnboardHostRequest"
	OnboardHostRequestFieldResourceId  = "resourceId"
	OnboardHostRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "OnboardHostResponse"

	// Fields and Edges constants for "CreateInstanceRequest"
	CreateInstanceRequestEdgeInstance     = "instance"
	CreateInstanceRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "CreateInstanceResponse"
	CreateInstanceResponseEdgeInstance = "instance"

	// Fields and Edges constants for "GetInstanceRequest"
	GetInstanceRequestFieldResourceId  = "resourceId"
	GetInstanceRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "GetInstanceResponse"
	GetInstanceResponseEdgeInstance = "instance"

	// Fields and Edges constants for "ListInstancesRequest"
	ListInstancesRequestFieldOrderBy     = "order_by"
	ListInstancesRequestFieldFilter      = "filter"
	ListInstancesRequestFieldPageSize    = "page_size"
	ListInstancesRequestFieldOffset      = "offset"
	ListInstancesRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "ListInstancesResponse"
	ListInstancesResponseEdgeInstances      = "instances"
	ListInstancesResponseFieldTotalElements = "total_elements"
	ListInstancesResponseFieldHasNext       = "has_next"

	// Fields and Edges constants for "UpdateInstanceRequest"
	UpdateInstanceRequestFieldResourceId  = "resourceId"
	UpdateInstanceRequestEdgeInstance     = "instance"
	UpdateInstanceRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "PatchInstanceRequest"
	PatchInstanceRequestFieldResourceId  = "resourceId"
	PatchInstanceRequestEdgeInstance     = "instance"
	PatchInstanceRequestEdgeFieldMask    = "field_mask"
	PatchInstanceRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "DeleteInstanceRequest"
	DeleteInstanceRequestFieldResourceId  = "resourceId"
	DeleteInstanceRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "DeleteInstanceResponse"

	// Fields and Edges constants for "InvalidateInstanceRequest"
	InvalidateInstanceRequestFieldResourceId  = "resourceId"
	InvalidateInstanceRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "InvalidateInstanceResponse"

	// Fields and Edges constants for "CreateOperatingSystemRequest"
	CreateOperatingSystemRequestEdgeOs           = "os"
	CreateOperatingSystemRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "CreateOperatingSystemResponse"
	CreateOperatingSystemResponseEdgeOs = "os"

	// Fields and Edges constants for "GetOperatingSystemRequest"
	GetOperatingSystemRequestFieldResourceId  = "resourceId"
	GetOperatingSystemRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "GetOperatingSystemResponse"
	GetOperatingSystemResponseEdgeOs = "os"

	// Fields and Edges constants for "ListOperatingSystemsRequest"
	ListOperatingSystemsRequestFieldOrderBy     = "order_by"
	ListOperatingSystemsRequestFieldFilter      = "filter"
	ListOperatingSystemsRequestFieldPageSize    = "page_size"
	ListOperatingSystemsRequestFieldOffset      = "offset"
	ListOperatingSystemsRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "ListOperatingSystemsResponse"
	ListOperatingSystemsResponseEdgeOperatingSystemResources = "Operating_system_resources"
	ListOperatingSystemsResponseFieldTotalElements           = "total_elements"
	ListOperatingSystemsResponseFieldHasNext                 = "has_next"

	// Fields and Edges constants for "UpdateOperatingSystemRequest"
	UpdateOperatingSystemRequestFieldResourceId  = "resourceId"
	UpdateOperatingSystemRequestEdgeOs           = "os"
	UpdateOperatingSystemRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "PatchOperatingSystemRequest"
	PatchOperatingSystemRequestFieldResourceId  = "resourceId"
	PatchOperatingSystemRequestEdgeOs           = "os"
	PatchOperatingSystemRequestEdgeFieldMask    = "field_mask"
	PatchOperatingSystemRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "DeleteOperatingSystemRequest"
	DeleteOperatingSystemRequestFieldResourceId  = "resourceId"
	DeleteOperatingSystemRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "DeleteOperatingSystemResponse"

	// Fields and Edges constants for "CreateProviderRequest"
	CreateProviderRequestEdgeProvider     = "provider"
	CreateProviderRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "CreateProviderResponse"
	CreateProviderResponseEdgeProvider = "provider"

	// Fields and Edges constants for "GetProviderRequest"
	GetProviderRequestFieldResourceId  = "resourceId"
	GetProviderRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "GetProviderResponse"
	GetProviderResponseEdgeProvider = "provider"

	// Fields and Edges constants for "ListProvidersRequest"
	ListProvidersRequestFieldOrderBy     = "order_by"
	ListProvidersRequestFieldFilter      = "filter"
	ListProvidersRequestFieldPageSize    = "page_size"
	ListProvidersRequestFieldOffset      = "offset"
	ListProvidersRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "ListProvidersResponse"
	ListProvidersResponseEdgeProviders      = "providers"
	ListProvidersResponseFieldTotalElements = "total_elements"
	ListProvidersResponseFieldHasNext       = "has_next"

	// Fields and Edges constants for "DeleteProviderRequest"
	DeleteProviderRequestFieldResourceId  = "resourceId"
	DeleteProviderRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "DeleteProviderResponse"

	// Fields and Edges constants for "CreateWorkloadRequest"
	CreateWorkloadRequestEdgeWorkload     = "workload"
	CreateWorkloadRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "CreateWorkloadResponse"
	CreateWorkloadResponseEdgeWorkload = "workload"

	// Fields and Edges constants for "GetWorkloadRequest"
	GetWorkloadRequestFieldResourceId  = "resourceId"
	GetWorkloadRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "GetWorkloadResponse"
	GetWorkloadResponseEdgeWorkload = "workload"

	// Fields and Edges constants for "ListWorkloadsRequest"
	ListWorkloadsRequestFieldOrderBy     = "order_by"
	ListWorkloadsRequestFieldFilter      = "filter"
	ListWorkloadsRequestFieldPageSize    = "page_size"
	ListWorkloadsRequestFieldOffset      = "offset"
	ListWorkloadsRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "ListWorkloadsResponse"
	ListWorkloadsResponseEdgeWorkloads      = "workloads"
	ListWorkloadsResponseFieldTotalElements = "total_elements"
	ListWorkloadsResponseFieldHasNext       = "has_next"

	// Fields and Edges constants for "UpdateWorkloadRequest"
	UpdateWorkloadRequestFieldResourceId  = "resourceId"
	UpdateWorkloadRequestEdgeWorkload     = "workload"
	UpdateWorkloadRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "PatchWorkloadRequest"
	PatchWorkloadRequestFieldResourceId  = "resourceId"
	PatchWorkloadRequestEdgeWorkload     = "workload"
	PatchWorkloadRequestEdgeFieldMask    = "field_mask"
	PatchWorkloadRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "DeleteWorkloadRequest"
	DeleteWorkloadRequestFieldResourceId  = "resourceId"
	DeleteWorkloadRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "DeleteWorkloadResponse"

	// Fields and Edges constants for "CreateWorkloadMemberRequest"
	CreateWorkloadMemberRequestEdgeWorkloadMember = "workload_member"
	CreateWorkloadMemberRequestFieldProjectName   = "projectName"

	// Fields and Edges constants for "CreateWorkloadMemberResponse"
	CreateWorkloadMemberResponseEdgeWorkloadMember = "workload_member"

	// Fields and Edges constants for "GetWorkloadMemberRequest"
	GetWorkloadMemberRequestFieldResourceId  = "resourceId"
	GetWorkloadMemberRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "GetWorkloadMemberResponse"
	GetWorkloadMemberResponseEdgeWorkloadMember = "workload_member"

	// Fields and Edges constants for "ListWorkloadMembersRequest"
	ListWorkloadMembersRequestFieldOrderBy     = "order_by"
	ListWorkloadMembersRequestFieldFilter      = "filter"
	ListWorkloadMembersRequestFieldPageSize    = "page_size"
	ListWorkloadMembersRequestFieldOffset      = "offset"
	ListWorkloadMembersRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "ListWorkloadMembersResponse"
	ListWorkloadMembersResponseEdgeWorkloadMembers = "workload_members"
	ListWorkloadMembersResponseFieldTotalElements  = "total_elements"
	ListWorkloadMembersResponseFieldHasNext        = "has_next"

	// Fields and Edges constants for "DeleteWorkloadMemberRequest"
	DeleteWorkloadMemberRequestFieldResourceId  = "resourceId"
	DeleteWorkloadMemberRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "DeleteWorkloadMemberResponse"

	// Fields and Edges constants for "ListSchedulesRequest"
	ListSchedulesRequestFieldPageSize    = "page_size"
	ListSchedulesRequestFieldOffset      = "offset"
	ListSchedulesRequestFieldHostId      = "host_id"
	ListSchedulesRequestFieldSiteId      = "site_id"
	ListSchedulesRequestFieldRegionId    = "region_id"
	ListSchedulesRequestFieldUnixEpoch   = "unix_epoch"
	ListSchedulesRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "ListSchedulesResponse"
	ListSchedulesResponseEdgeSingleSchedules   = "single_schedules"
	ListSchedulesResponseEdgeRepeatedSchedules = "repeated_schedules"
	ListSchedulesResponseFieldTotalElements    = "total_elements"
	ListSchedulesResponseFieldHasNext          = "has_next"

	// Fields and Edges constants for "CreateSingleScheduleRequest"
	CreateSingleScheduleRequestEdgeSingleSchedule = "single_schedule"
	CreateSingleScheduleRequestFieldProjectName   = "projectName"

	// Fields and Edges constants for "CreateSingleScheduleResponse"
	CreateSingleScheduleResponseEdgeSingleSchedule = "single_schedule"

	// Fields and Edges constants for "GetSingleScheduleRequest"
	GetSingleScheduleRequestFieldResourceId  = "resourceId"
	GetSingleScheduleRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "GetSingleScheduleResponse"
	GetSingleScheduleResponseEdgeSingleSchedule = "single_schedule"

	// Fields and Edges constants for "ListSingleSchedulesRequest"
	ListSingleSchedulesRequestFieldPageSize    = "page_size"
	ListSingleSchedulesRequestFieldOffset      = "offset"
	ListSingleSchedulesRequestFieldHostId      = "host_id"
	ListSingleSchedulesRequestFieldSiteId      = "site_id"
	ListSingleSchedulesRequestFieldRegionId    = "region_id"
	ListSingleSchedulesRequestFieldUnixEpoch   = "unix_epoch"
	ListSingleSchedulesRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "ListSingleSchedulesResponse"
	ListSingleSchedulesResponseEdgeSingleSchedules = "single_schedules"
	ListSingleSchedulesResponseFieldTotalElements  = "total_elements"
	ListSingleSchedulesResponseFieldHasNext        = "has_next"

	// Fields and Edges constants for "UpdateSingleScheduleRequest"
	UpdateSingleScheduleRequestFieldResourceId    = "resourceId"
	UpdateSingleScheduleRequestEdgeSingleSchedule = "single_schedule"
	UpdateSingleScheduleRequestFieldProjectName   = "projectName"

	// Fields and Edges constants for "PatchSingleScheduleRequest"
	PatchSingleScheduleRequestFieldResourceId    = "resourceId"
	PatchSingleScheduleRequestEdgeSingleSchedule = "single_schedule"
	PatchSingleScheduleRequestEdgeFieldMask      = "field_mask"
	PatchSingleScheduleRequestFieldProjectName   = "projectName"

	// Fields and Edges constants for "DeleteSingleScheduleRequest"
	DeleteSingleScheduleRequestFieldResourceId  = "resourceId"
	DeleteSingleScheduleRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "DeleteSingleScheduleResponse"

	// Fields and Edges constants for "CreateRepeatedScheduleRequest"
	CreateRepeatedScheduleRequestEdgeRepeatedSchedule = "repeated_schedule"
	CreateRepeatedScheduleRequestFieldProjectName     = "projectName"

	// Fields and Edges constants for "CreateRepeatedScheduleResponse"
	CreateRepeatedScheduleResponseEdgeRepeatedSchedule = "repeated_schedule"

	// Fields and Edges constants for "GetRepeatedScheduleRequest"
	GetRepeatedScheduleRequestFieldResourceId  = "resourceId"
	GetRepeatedScheduleRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "GetRepeatedScheduleResponse"
	GetRepeatedScheduleResponseEdgeRepeatedSchedule = "repeated_schedule"

	// Fields and Edges constants for "ListRepeatedSchedulesRequest"
	ListRepeatedSchedulesRequestFieldPageSize    = "page_size"
	ListRepeatedSchedulesRequestFieldOffset      = "offset"
	ListRepeatedSchedulesRequestFieldHostId      = "host_id"
	ListRepeatedSchedulesRequestFieldSiteId      = "site_id"
	ListRepeatedSchedulesRequestFieldRegionId    = "region_id"
	ListRepeatedSchedulesRequestFieldUnixEpoch   = "unix_epoch"
	ListRepeatedSchedulesRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "ListRepeatedSchedulesResponse"
	ListRepeatedSchedulesResponseEdgeRepeatedSchedules = "repeated_schedules"
	ListRepeatedSchedulesResponseFieldTotalElements    = "total_elements"
	ListRepeatedSchedulesResponseFieldHasNext          = "has_next"

	// Fields and Edges constants for "UpdateRepeatedScheduleRequest"
	UpdateRepeatedScheduleRequestFieldResourceId      = "resourceId"
	UpdateRepeatedScheduleRequestEdgeRepeatedSchedule = "repeated_schedule"
	UpdateRepeatedScheduleRequestFieldProjectName     = "projectName"

	// Fields and Edges constants for "PatchRepeatedScheduleRequest"
	PatchRepeatedScheduleRequestFieldResourceId      = "resourceId"
	PatchRepeatedScheduleRequestEdgeRepeatedSchedule = "repeated_schedule"
	PatchRepeatedScheduleRequestEdgeFieldMask        = "field_mask"
	PatchRepeatedScheduleRequestFieldProjectName     = "projectName"

	// Fields and Edges constants for "DeleteRepeatedScheduleRequest"
	DeleteRepeatedScheduleRequestFieldResourceId  = "resourceId"
	DeleteRepeatedScheduleRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "DeleteRepeatedScheduleResponse"

	// Fields and Edges constants for "CreateTelemetryLogsGroupRequest"
	CreateTelemetryLogsGroupRequestEdgeTelemetryLogsGroup = "telemetry_logs_group"
	CreateTelemetryLogsGroupRequestFieldProjectName       = "projectName"

	// Fields and Edges constants for "CreateTelemetryLogsGroupResponse"
	CreateTelemetryLogsGroupResponseEdgeTelemetryLogsGroup = "telemetry_logs_group"

	// Fields and Edges constants for "GetTelemetryLogsGroupRequest"
	GetTelemetryLogsGroupRequestFieldResourceId  = "resourceId"
	GetTelemetryLogsGroupRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "GetTelemetryLogsGroupResponse"
	GetTelemetryLogsGroupResponseEdgeTelemetryLogsGroup = "telemetry_logs_group"

	// Fields and Edges constants for "ListTelemetryLogsGroupsRequest"
	ListTelemetryLogsGroupsRequestFieldPageSize    = "page_size"
	ListTelemetryLogsGroupsRequestFieldOffset      = "offset"
	ListTelemetryLogsGroupsRequestFieldOrderBy     = "order_by"
	ListTelemetryLogsGroupsRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "ListTelemetryLogsGroupsResponse"
	ListTelemetryLogsGroupsResponseEdgeTelemetryLogsGroups = "telemetry_logs_groups"
	ListTelemetryLogsGroupsResponseFieldTotalElements      = "total_elements"
	ListTelemetryLogsGroupsResponseFieldHasNext            = "has_next"

	// Fields and Edges constants for "DeleteTelemetryLogsGroupRequest"
	DeleteTelemetryLogsGroupRequestFieldResourceId  = "resourceId"
	DeleteTelemetryLogsGroupRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "DeleteTelemetryLogsGroupResponse"

	// Fields and Edges constants for "CreateTelemetryMetricsGroupRequest"
	CreateTelemetryMetricsGroupRequestEdgeTelemetryMetricsGroup = "telemetry_metrics_group"
	CreateTelemetryMetricsGroupRequestFieldProjectName          = "projectName"

	// Fields and Edges constants for "CreateTelemetryMetricsGroupResponse"
	CreateTelemetryMetricsGroupResponseEdgeTelemetryMetricsGroup = "telemetry_metrics_group"

	// Fields and Edges constants for "GetTelemetryMetricsGroupRequest"
	GetTelemetryMetricsGroupRequestFieldResourceId  = "resourceId"
	GetTelemetryMetricsGroupRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "GetTelemetryMetricsGroupResponse"
	GetTelemetryMetricsGroupResponseEdgeTelemetryMetricsGroup = "telemetry_metrics_group"

	// Fields and Edges constants for "ListTelemetryMetricsGroupsRequest"
	ListTelemetryMetricsGroupsRequestFieldPageSize    = "page_size"
	ListTelemetryMetricsGroupsRequestFieldOffset      = "offset"
	ListTelemetryMetricsGroupsRequestFieldOrderBy     = "order_by"
	ListTelemetryMetricsGroupsRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "ListTelemetryMetricsGroupsResponse"
	ListTelemetryMetricsGroupsResponseEdgeTelemetryMetricsGroups = "telemetry_metrics_groups"
	ListTelemetryMetricsGroupsResponseFieldTotalElements         = "total_elements"
	ListTelemetryMetricsGroupsResponseFieldHasNext               = "has_next"

	// Fields and Edges constants for "DeleteTelemetryMetricsGroupRequest"
	DeleteTelemetryMetricsGroupRequestFieldResourceId  = "resourceId"
	DeleteTelemetryMetricsGroupRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "DeleteTelemetryMetricsGroupResponse"

	// Fields and Edges constants for "CreateTelemetryLogsProfileRequest"
	CreateTelemetryLogsProfileRequestEdgeTelemetryLogsProfile = "telemetry_logs_profile"
	CreateTelemetryLogsProfileRequestFieldProjectName         = "projectName"

	// Fields and Edges constants for "CreateTelemetryLogsProfileResponse"
	CreateTelemetryLogsProfileResponseEdgeTelemetryLogsProfile = "telemetry_logs_profile"

	// Fields and Edges constants for "GetTelemetryLogsProfileRequest"
	GetTelemetryLogsProfileRequestFieldResourceId  = "resourceId"
	GetTelemetryLogsProfileRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "GetTelemetryLogsProfileResponse"
	GetTelemetryLogsProfileResponseEdgeTelemetryLogsProfile = "telemetry_logs_profile"

	// Fields and Edges constants for "ListTelemetryLogsProfilesRequest"
	ListTelemetryLogsProfilesRequestFieldPageSize      = "page_size"
	ListTelemetryLogsProfilesRequestFieldOffset        = "offset"
	ListTelemetryLogsProfilesRequestFieldOrderBy       = "order_by"
	ListTelemetryLogsProfilesRequestFieldInstanceId    = "instance_id"
	ListTelemetryLogsProfilesRequestFieldSiteId        = "site_id"
	ListTelemetryLogsProfilesRequestFieldRegionId      = "region_id"
	ListTelemetryLogsProfilesRequestFieldShowInherited = "show_inherited"
	ListTelemetryLogsProfilesRequestFieldProjectName   = "projectName"

	// Fields and Edges constants for "ListTelemetryLogsProfilesResponse"
	ListTelemetryLogsProfilesResponseEdgeTelemetryLogsProfiles = "telemetry_logs_profiles"
	ListTelemetryLogsProfilesResponseFieldTotalElements        = "total_elements"
	ListTelemetryLogsProfilesResponseFieldHasNext              = "has_next"

	// Fields and Edges constants for "UpdateTelemetryLogsProfileRequest"
	UpdateTelemetryLogsProfileRequestFieldResourceId          = "resourceId"
	UpdateTelemetryLogsProfileRequestEdgeTelemetryLogsProfile = "telemetry_logs_profile"
	UpdateTelemetryLogsProfileRequestFieldProjectName         = "projectName"

	// Fields and Edges constants for "PatchTelemetryLogsProfileRequest"
	PatchTelemetryLogsProfileRequestFieldResourceId          = "resourceId"
	PatchTelemetryLogsProfileRequestEdgeTelemetryLogsProfile = "telemetry_logs_profile"
	PatchTelemetryLogsProfileRequestEdgeFieldMask            = "field_mask"
	PatchTelemetryLogsProfileRequestFieldProjectName         = "projectName"

	// Fields and Edges constants for "DeleteTelemetryLogsProfileRequest"
	DeleteTelemetryLogsProfileRequestFieldResourceId  = "resourceId"
	DeleteTelemetryLogsProfileRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "DeleteTelemetryLogsProfileResponse"

	// Fields and Edges constants for "CreateTelemetryMetricsProfileRequest"
	CreateTelemetryMetricsProfileRequestEdgeTelemetryMetricsProfile = "telemetry_metrics_profile"
	CreateTelemetryMetricsProfileRequestFieldProjectName            = "projectName"

	// Fields and Edges constants for "CreateTelemetryMetricsProfileResponse"
	CreateTelemetryMetricsProfileResponseEdgeTelemetryMetricsProfile = "telemetry_metrics_profile"

	// Fields and Edges constants for "GetTelemetryMetricsProfileRequest"
	GetTelemetryMetricsProfileRequestFieldResourceId  = "resourceId"
	GetTelemetryMetricsProfileRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "GetTelemetryMetricsProfileResponse"
	GetTelemetryMetricsProfileResponseEdgeTelemetryMetricsProfile = "telemetry_metrics_profile"

	// Fields and Edges constants for "ListTelemetryMetricsProfilesRequest"
	ListTelemetryMetricsProfilesRequestFieldPageSize      = "page_size"
	ListTelemetryMetricsProfilesRequestFieldOffset        = "offset"
	ListTelemetryMetricsProfilesRequestFieldOrderBy       = "order_by"
	ListTelemetryMetricsProfilesRequestFieldInstanceId    = "instance_id"
	ListTelemetryMetricsProfilesRequestFieldSiteId        = "site_id"
	ListTelemetryMetricsProfilesRequestFieldRegionId      = "region_id"
	ListTelemetryMetricsProfilesRequestFieldShowInherited = "show_inherited"
	ListTelemetryMetricsProfilesRequestFieldProjectName   = "projectName"

	// Fields and Edges constants for "ListTelemetryMetricsProfilesResponse"
	ListTelemetryMetricsProfilesResponseEdgeTelemetryMetricsProfiles = "telemetry_metrics_profiles"
	ListTelemetryMetricsProfilesResponseFieldTotalElements           = "total_elements"
	ListTelemetryMetricsProfilesResponseFieldHasNext                 = "has_next"

	// Fields and Edges constants for "UpdateTelemetryMetricsProfileRequest"
	UpdateTelemetryMetricsProfileRequestFieldResourceId             = "resourceId"
	UpdateTelemetryMetricsProfileRequestEdgeTelemetryMetricsProfile = "telemetry_metrics_profile"
	UpdateTelemetryMetricsProfileRequestFieldProjectName            = "projectName"

	// Fields and Edges constants for "PatchTelemetryMetricsProfileRequest"
	PatchTelemetryMetricsProfileRequestFieldResourceId             = "resourceId"
	PatchTelemetryMetricsProfileRequestEdgeTelemetryMetricsProfile = "telemetry_metrics_profile"
	PatchTelemetryMetricsProfileRequestEdgeFieldMask               = "field_mask"
	PatchTelemetryMetricsProfileRequestFieldProjectName            = "projectName"

	// Fields and Edges constants for "DeleteTelemetryMetricsProfileRequest"
	DeleteTelemetryMetricsProfileRequestFieldResourceId  = "resourceId"
	DeleteTelemetryMetricsProfileRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "DeleteTelemetryMetricsProfileResponse"

	// Fields and Edges constants for "CreateLocalAccountRequest"
	CreateLocalAccountRequestEdgeLocalAccount = "local_account"
	CreateLocalAccountRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "CreateLocalAccountResponse"
	CreateLocalAccountResponseEdgeLocalAccount = "local_account"

	// Fields and Edges constants for "GetLocalAccountRequest"
	GetLocalAccountRequestFieldResourceId  = "resourceId"
	GetLocalAccountRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "GetLocalAccountResponse"
	GetLocalAccountResponseEdgeLocalAccount = "local_account"

	// Fields and Edges constants for "ListLocalAccountsRequest"
	ListLocalAccountsRequestFieldOrderBy     = "order_by"
	ListLocalAccountsRequestFieldFilter      = "filter"
	ListLocalAccountsRequestFieldPageSize    = "page_size"
	ListLocalAccountsRequestFieldOffset      = "offset"
	ListLocalAccountsRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "ListLocalAccountsResponse"
	ListLocalAccountsResponseEdgeLocalAccounts  = "local_accounts"
	ListLocalAccountsResponseFieldTotalElements = "total_elements"
	ListLocalAccountsResponseFieldHasNext       = "has_next"

	// Fields and Edges constants for "DeleteLocalAccountRequest"
	DeleteLocalAccountRequestFieldResourceId  = "resourceId"
	DeleteLocalAccountRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "DeleteLocalAccountResponse"

	// Fields and Edges constants for "CreateOSUpdatePolicyRequest"
	CreateOSUpdatePolicyRequestEdgeOsUpdatePolicy = "os_update_policy"
	CreateOSUpdatePolicyRequestFieldProjectName   = "projectName"

	// Fields and Edges constants for "CreateOSUpdatePolicyResponse"
	CreateOSUpdatePolicyResponseEdgeOsUpdatePolicy = "os_update_policy"

	// Fields and Edges constants for "GetOSUpdatePolicyRequest"
	GetOSUpdatePolicyRequestFieldResourceId  = "resourceId"
	GetOSUpdatePolicyRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "GetOSUpdatePolicyResponse"
	GetOSUpdatePolicyResponseEdgeOsUpdatePolicy = "os_update_policy"

	// Fields and Edges constants for "ListOSUpdatePolicyRequest"
	ListOSUpdatePolicyRequestFieldOrderBy     = "order_by"
	ListOSUpdatePolicyRequestFieldFilter      = "filter"
	ListOSUpdatePolicyRequestFieldPageSize    = "page_size"
	ListOSUpdatePolicyRequestFieldOffset      = "offset"
	ListOSUpdatePolicyRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "ListOSUpdatePolicyResponse"
	ListOSUpdatePolicyResponseEdgeOsUpdatePolicies = "os_update_policies"
	ListOSUpdatePolicyResponseFieldTotalElements   = "total_elements"
	ListOSUpdatePolicyResponseFieldHasNext         = "has_next"

	// Fields and Edges constants for "DeleteOSUpdatePolicyRequest"
	DeleteOSUpdatePolicyRequestFieldResourceId  = "resourceId"
	DeleteOSUpdatePolicyRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "DeleteOSUpdatePolicyResponse"

	// Fields and Edges constants for "CreateOSUpdateRunRequest"
	CreateOSUpdateRunRequestEdgeOsUpdateRun  = "os_update_run"
	CreateOSUpdateRunRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "CreateOSUpdateRunResponse"
	CreateOSUpdateRunResponseEdgeOsUpdateRun = "os_update_run"

	// Fields and Edges constants for "GetOSUpdateRunRequest"
	GetOSUpdateRunRequestFieldResourceId  = "resourceId"
	GetOSUpdateRunRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "GetOSUpdateRunResponse"
	GetOSUpdateRunResponseEdgeOsUpdateRun = "os_update_run"

	// Fields and Edges constants for "ListOSUpdateRunRequest"
	ListOSUpdateRunRequestFieldOrderBy     = "order_by"
	ListOSUpdateRunRequestFieldFilter      = "filter"
	ListOSUpdateRunRequestFieldPageSize    = "page_size"
	ListOSUpdateRunRequestFieldOffset      = "offset"
	ListOSUpdateRunRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "ListOSUpdateRunResponse"
	ListOSUpdateRunResponseEdgeOsUpdateRuns   = "os_update_runs"
	ListOSUpdateRunResponseFieldTotalElements = "total_elements"
	ListOSUpdateRunResponseFieldHasNext       = "has_next"

	// Fields and Edges constants for "DeleteOSUpdateRunRequest"
	DeleteOSUpdateRunRequestFieldResourceId  = "resourceId"
	DeleteOSUpdateRunRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "DeleteOSUpdateRunResponse"

	// Fields and Edges constants for "CreateCustomConfigRequest"
	CreateCustomConfigRequestEdgeCustomConfig = "custom_config"
	CreateCustomConfigRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "CreateCustomConfigResponse"
	CreateCustomConfigResponseEdgeCustomConfig = "custom_config"

	// Fields and Edges constants for "GetCustomConfigRequest"
	GetCustomConfigRequestFieldResourceId  = "resourceId"
	GetCustomConfigRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "GetCustomConfigResponse"
	GetCustomConfigResponseEdgeCustomConfig = "custom_config"

	// Fields and Edges constants for "ListCustomConfigsRequest"
	ListCustomConfigsRequestFieldOrderBy     = "order_by"
	ListCustomConfigsRequestFieldFilter      = "filter"
	ListCustomConfigsRequestFieldPageSize    = "page_size"
	ListCustomConfigsRequestFieldOffset      = "offset"
	ListCustomConfigsRequestFieldProjectName = "projectName"

	// Fields and Edges constants for "ListCustomConfigsResponse"
	ListCustomConfigsResponseEdgeCustomConfigs  = "custom_configs"
	ListCustomConfigsResponseFieldTotalElements = "total_elements"
	ListCustomConfigsResponseFieldHasNext       = "has_next"

	// Fields and Edges constants for "DeleteCustomConfigRequest"
	DeleteCustomConfigRequestFieldResourceId  = "resourceId"
	DeleteCustomConfigRequestFieldProjectName = "projectName"

// Fields and Edges constants for "DeleteCustomConfigResponse"

)
