// Code generated by protoc-gen-go-const. DO NOT EDIT.

// source: services/v1/services.proto

package servicesv1

const (
	// Fields and Edges constants for "CreateRegionRequest"
	CreateRegionRequestEdgeRegion = "region"

	// Fields and Edges constants for "CreateRegionResponse"
	CreateRegionResponseEdgeRegion = "region"

	// Fields and Edges constants for "GetRegionRequest"
	GetRegionRequestFieldResourceId = "resource_id"

	// Fields and Edges constants for "GetRegionResponse"
	GetRegionResponseEdgeRegion = "region"

	// Fields and Edges constants for "ListRegionsRequest"
	ListRegionsRequestFieldOrderBy        = "order_by"
	ListRegionsRequestFieldFilter         = "filter"
	ListRegionsRequestFieldPageSize       = "page_size"
	ListRegionsRequestFieldOffset         = "offset"
	ListRegionsRequestFieldShowTotalSites = "show_total_sites"

	// Fields and Edges constants for "ListRegionsResponse"
	ListRegionsResponseEdgeRegions        = "regions"
	ListRegionsResponseFieldTotalElements = "total_elements"
	ListRegionsResponseFieldHasNext       = "has_next"

	// Fields and Edges constants for "UpdateRegionRequest"
	UpdateRegionRequestFieldResourceId = "resource_id"
	UpdateRegionRequestEdgeRegion      = "region"

	// Fields and Edges constants for "PatchRegionRequest"
	PatchRegionRequestFieldResourceId = "resource_id"
	PatchRegionRequestEdgeRegion      = "region"
	PatchRegionRequestEdgeFieldMask   = "field_mask"

	// Fields and Edges constants for "DeleteRegionRequest"
	DeleteRegionRequestFieldResourceId = "resource_id"

	// Fields and Edges constants for "DeleteRegionResponse"

	// Fields and Edges constants for "CreateSiteRequest"
	CreateSiteRequestEdgeSite = "site"

	// Fields and Edges constants for "CreateSiteResponse"
	CreateSiteResponseEdgeSite = "site"

	// Fields and Edges constants for "GetSiteRequest"
	GetSiteRequestFieldResourceId = "resource_id"

	// Fields and Edges constants for "GetSiteResponse"
	GetSiteResponseEdgeSite = "site"

	// Fields and Edges constants for "ListSitesRequest"
	ListSitesRequestFieldOrderBy  = "order_by"
	ListSitesRequestFieldFilter   = "filter"
	ListSitesRequestFieldPageSize = "page_size"
	ListSitesRequestFieldOffset   = "offset"

	// Fields and Edges constants for "ListSitesResponse"
	ListSitesResponseEdgeSites          = "sites"
	ListSitesResponseFieldTotalElements = "total_elements"
	ListSitesResponseFieldHasNext       = "has_next"

	// Fields and Edges constants for "UpdateSiteRequest"
	UpdateSiteRequestFieldResourceId = "resource_id"
	UpdateSiteRequestEdgeSite        = "site"

	// Fields and Edges constants for "PatchSiteRequest"
	PatchSiteRequestFieldResourceId = "resource_id"
	PatchSiteRequestEdgeSite        = "site"
	PatchSiteRequestEdgeFieldMask   = "field_mask"

	// Fields and Edges constants for "DeleteSiteRequest"
	DeleteSiteRequestFieldResourceId = "resource_id"

	// Fields and Edges constants for "DeleteSiteResponse"

	// Fields and Edges constants for "ListLocationsRequest"
	ListLocationsRequestFieldName        = "name"
	ListLocationsRequestFieldShowSites   = "show_sites"
	ListLocationsRequestFieldShowRegions = "show_regions"

	// Fields and Edges constants for "ListLocationsResponse"
	ListLocationsResponseEdgeNodes           = "nodes"
	ListLocationsResponseFieldTotalElements  = "total_elements"
	ListLocationsResponseFieldOutputElements = "output_elements"

	// Fields and Edges constants for "GetHostSummaryRequest"
	GetHostSummaryRequestFieldFilter = "filter"

	// Fields and Edges constants for "GetHostSummaryResponse"
	GetHostSummaryResponseFieldTotal       = "total"
	GetHostSummaryResponseFieldError       = "error"
	GetHostSummaryResponseFieldRunning     = "running"
	GetHostSummaryResponseFieldUnallocated = "unallocated"

	// Fields and Edges constants for "CreateHostRequest"
	CreateHostRequestEdgeHost = "host"

	// Fields and Edges constants for "CreateHostResponse"
	CreateHostResponseEdgeHost = "host"

	// Fields and Edges constants for "GetHostRequest"
	GetHostRequestFieldResourceId = "resource_id"

	// Fields and Edges constants for "GetHostResponse"
	GetHostResponseEdgeHost = "host"

	// Fields and Edges constants for "ListHostsRequest"
	ListHostsRequestFieldOrderBy  = "order_by"
	ListHostsRequestFieldFilter   = "filter"
	ListHostsRequestFieldPageSize = "page_size"
	ListHostsRequestFieldOffset   = "offset"

	// Fields and Edges constants for "ListHostsResponse"
	ListHostsResponseEdgeHosts          = "hosts"
	ListHostsResponseFieldTotalElements = "total_elements"
	ListHostsResponseFieldHasNext       = "has_next"

	// Fields and Edges constants for "UpdateHostRequest"
	UpdateHostRequestFieldResourceId = "resource_id"
	UpdateHostRequestEdgeHost        = "host"

	// Fields and Edges constants for "PatchHostRequest"
	PatchHostRequestFieldResourceId = "resource_id"
	PatchHostRequestEdgeHost        = "host"
	PatchHostRequestEdgeFieldMask   = "field_mask"

	// Fields and Edges constants for "DeleteHostRequest"
	DeleteHostRequestFieldResourceId = "resource_id"

	// Fields and Edges constants for "DeleteHostResponse"

	// Fields and Edges constants for "InvalidateHostRequest"
	InvalidateHostRequestFieldResourceId = "resource_id"
	InvalidateHostRequestFieldNote       = "note"

	// Fields and Edges constants for "InvalidateHostResponse"

	// Fields and Edges constants for "HostRegister"
	HostRegisterFieldName         = "name"
	HostRegisterFieldSerialNumber = "serial_number"
	HostRegisterFieldUuid         = "uuid"
	HostRegisterFieldAutoOnboard  = "auto_onboard"

	// Fields and Edges constants for "RegisterHostRequest"
	RegisterHostRequestFieldResourceId = "resource_id"
	RegisterHostRequestEdgeHost        = "host"

	// Fields and Edges constants for "OnboardHostRequest"
	OnboardHostRequestFieldResourceId = "resource_id"

	// Fields and Edges constants for "OnboardHostResponse"

	// Fields and Edges constants for "CreateInstanceRequest"
	CreateInstanceRequestEdgeInstance = "instance"

	// Fields and Edges constants for "CreateInstanceResponse"
	CreateInstanceResponseEdgeInstance = "instance"

	// Fields and Edges constants for "GetInstanceRequest"
	GetInstanceRequestFieldResourceId = "resource_id"

	// Fields and Edges constants for "GetInstanceResponse"
	GetInstanceResponseEdgeInstance = "instance"

	// Fields and Edges constants for "ListInstancesRequest"
	ListInstancesRequestFieldOrderBy  = "order_by"
	ListInstancesRequestFieldFilter   = "filter"
	ListInstancesRequestFieldPageSize = "page_size"
	ListInstancesRequestFieldOffset   = "offset"

	// Fields and Edges constants for "ListInstancesResponse"
	ListInstancesResponseEdgeInstances      = "instances"
	ListInstancesResponseFieldTotalElements = "total_elements"
	ListInstancesResponseFieldHasNext       = "has_next"

	// Fields and Edges constants for "UpdateInstanceRequest"
	UpdateInstanceRequestFieldResourceId = "resource_id"
	UpdateInstanceRequestEdgeInstance    = "instance"

	// Fields and Edges constants for "PatchInstanceRequest"
	PatchInstanceRequestFieldResourceId = "resource_id"
	PatchInstanceRequestEdgeInstance    = "instance"
	PatchInstanceRequestEdgeFieldMask   = "field_mask"

	// Fields and Edges constants for "DeleteInstanceRequest"
	DeleteInstanceRequestFieldResourceId = "resource_id"

	// Fields and Edges constants for "DeleteInstanceResponse"

	// Fields and Edges constants for "InvalidateInstanceRequest"
	InvalidateInstanceRequestFieldResourceId = "resource_id"

	// Fields and Edges constants for "InvalidateInstanceResponse"

	// Fields and Edges constants for "CreateOperatingSystemRequest"
	CreateOperatingSystemRequestEdgeOs = "os"

	// Fields and Edges constants for "CreateOperatingSystemResponse"
	CreateOperatingSystemResponseEdgeOs = "os"

	// Fields and Edges constants for "GetOperatingSystemRequest"
	GetOperatingSystemRequestFieldResourceId = "resource_id"

	// Fields and Edges constants for "GetOperatingSystemResponse"
	GetOperatingSystemResponseEdgeOs = "os"

	// Fields and Edges constants for "ListOperatingSystemsRequest"
	ListOperatingSystemsRequestFieldOrderBy  = "order_by"
	ListOperatingSystemsRequestFieldFilter   = "filter"
	ListOperatingSystemsRequestFieldPageSize = "page_size"
	ListOperatingSystemsRequestFieldOffset   = "offset"

	// Fields and Edges constants for "ListOperatingSystemsResponse"
	ListOperatingSystemsResponseEdgeOperatingSystemResources = "Operating_system_resources"
	ListOperatingSystemsResponseFieldTotalElements           = "total_elements"
	ListOperatingSystemsResponseFieldHasNext                 = "has_next"

	// Fields and Edges constants for "UpdateOperatingSystemRequest"
	UpdateOperatingSystemRequestFieldResourceId = "resource_id"
	UpdateOperatingSystemRequestEdgeOs          = "os"

	// Fields and Edges constants for "PatchOperatingSystemRequest"
	PatchOperatingSystemRequestFieldResourceId = "resource_id"
	PatchOperatingSystemRequestEdgeOs          = "os"
	PatchOperatingSystemRequestEdgeFieldMask   = "field_mask"

	// Fields and Edges constants for "DeleteOperatingSystemRequest"
	DeleteOperatingSystemRequestFieldResourceId = "resource_id"

	// Fields and Edges constants for "DeleteOperatingSystemResponse"

	// Fields and Edges constants for "CreateProviderRequest"
	CreateProviderRequestEdgeProvider = "provider"

	// Fields and Edges constants for "CreateProviderResponse"
	CreateProviderResponseEdgeProvider = "provider"

	// Fields and Edges constants for "GetProviderRequest"
	GetProviderRequestFieldResourceId = "resource_id"

	// Fields and Edges constants for "GetProviderResponse"
	GetProviderResponseEdgeProvider = "provider"

	// Fields and Edges constants for "ListProvidersRequest"
	ListProvidersRequestFieldOrderBy  = "order_by"
	ListProvidersRequestFieldFilter   = "filter"
	ListProvidersRequestFieldPageSize = "page_size"
	ListProvidersRequestFieldOffset   = "offset"

	// Fields and Edges constants for "ListProvidersResponse"
	ListProvidersResponseEdgeProviders      = "providers"
	ListProvidersResponseFieldTotalElements = "total_elements"
	ListProvidersResponseFieldHasNext       = "has_next"

	// Fields and Edges constants for "DeleteProviderRequest"
	DeleteProviderRequestFieldResourceId = "resource_id"

	// Fields and Edges constants for "DeleteProviderResponse"

	// Fields and Edges constants for "CreateWorkloadRequest"
	CreateWorkloadRequestEdgeWorkload = "workload"

	// Fields and Edges constants for "CreateWorkloadResponse"
	CreateWorkloadResponseEdgeWorkload = "workload"

	// Fields and Edges constants for "GetWorkloadRequest"
	GetWorkloadRequestFieldResourceId = "resource_id"

	// Fields and Edges constants for "GetWorkloadResponse"
	GetWorkloadResponseEdgeWorkload = "workload"

	// Fields and Edges constants for "ListWorkloadsRequest"
	ListWorkloadsRequestFieldOrderBy  = "order_by"
	ListWorkloadsRequestFieldFilter   = "filter"
	ListWorkloadsRequestFieldPageSize = "page_size"
	ListWorkloadsRequestFieldOffset   = "offset"

	// Fields and Edges constants for "ListWorkloadsResponse"
	ListWorkloadsResponseEdgeWorkloads      = "workloads"
	ListWorkloadsResponseFieldTotalElements = "total_elements"
	ListWorkloadsResponseFieldHasNext       = "has_next"

	// Fields and Edges constants for "UpdateWorkloadRequest"
	UpdateWorkloadRequestFieldResourceId = "resource_id"
	UpdateWorkloadRequestEdgeWorkload    = "workload"

	// Fields and Edges constants for "PatchWorkloadRequest"
	PatchWorkloadRequestFieldResourceId = "resource_id"
	PatchWorkloadRequestEdgeWorkload    = "workload"
	PatchWorkloadRequestEdgeFieldMask   = "field_mask"

	// Fields and Edges constants for "DeleteWorkloadRequest"
	DeleteWorkloadRequestFieldResourceId = "resource_id"

	// Fields and Edges constants for "DeleteWorkloadResponse"

	// Fields and Edges constants for "CreateWorkloadMemberRequest"
	CreateWorkloadMemberRequestEdgeWorkloadMember = "workload_member"

	// Fields and Edges constants for "CreateWorkloadMemberResponse"
	CreateWorkloadMemberResponseEdgeWorkloadMember = "workload_member"

	// Fields and Edges constants for "GetWorkloadMemberRequest"
	GetWorkloadMemberRequestFieldResourceId = "resource_id"

	// Fields and Edges constants for "GetWorkloadMemberResponse"
	GetWorkloadMemberResponseEdgeWorkloadMember = "workload_member"

	// Fields and Edges constants for "ListWorkloadMembersRequest"
	ListWorkloadMembersRequestFieldOrderBy  = "order_by"
	ListWorkloadMembersRequestFieldFilter   = "filter"
	ListWorkloadMembersRequestFieldPageSize = "page_size"
	ListWorkloadMembersRequestFieldOffset   = "offset"

	// Fields and Edges constants for "ListWorkloadMembersResponse"
	ListWorkloadMembersResponseEdgeWorkloadMembers = "workload_members"
	ListWorkloadMembersResponseFieldTotalElements  = "total_elements"
	ListWorkloadMembersResponseFieldHasNext        = "has_next"

	// Fields and Edges constants for "DeleteWorkloadMemberRequest"
	DeleteWorkloadMemberRequestFieldResourceId = "resource_id"

	// Fields and Edges constants for "DeleteWorkloadMemberResponse"

	// Fields and Edges constants for "ListSchedulesRequest"
	ListSchedulesRequestFieldPageSize  = "page_size"
	ListSchedulesRequestFieldOffset    = "offset"
	ListSchedulesRequestFieldHostId    = "host_id"
	ListSchedulesRequestFieldSiteId    = "site_id"
	ListSchedulesRequestFieldRegionId  = "region_id"
	ListSchedulesRequestFieldUnixEpoch = "unix_epoch"

	// Fields and Edges constants for "ListSchedulesResponse"
	ListSchedulesResponseEdgeSingleSchedules   = "single_schedules"
	ListSchedulesResponseEdgeRepeatedSchedules = "repeated_schedules"
	ListSchedulesResponseFieldTotalElements    = "total_elements"
	ListSchedulesResponseFieldHasNext          = "has_next"

	// Fields and Edges constants for "CreateSingleScheduleRequest"
	CreateSingleScheduleRequestEdgeSingleSchedule = "single_schedule"

	// Fields and Edges constants for "CreateSingleScheduleResponse"
	CreateSingleScheduleResponseEdgeSingleSchedule = "single_schedule"

	// Fields and Edges constants for "GetSingleScheduleRequest"
	GetSingleScheduleRequestFieldResourceId = "resource_id"

	// Fields and Edges constants for "GetSingleScheduleResponse"
	GetSingleScheduleResponseEdgeSingleSchedule = "single_schedule"

	// Fields and Edges constants for "ListSingleSchedulesRequest"
	ListSingleSchedulesRequestFieldPageSize  = "page_size"
	ListSingleSchedulesRequestFieldOffset    = "offset"
	ListSingleSchedulesRequestFieldHostId    = "host_id"
	ListSingleSchedulesRequestFieldSiteId    = "site_id"
	ListSingleSchedulesRequestFieldRegionId  = "region_id"
	ListSingleSchedulesRequestFieldUnixEpoch = "unix_epoch"

	// Fields and Edges constants for "ListSingleSchedulesResponse"
	ListSingleSchedulesResponseEdgeSingleSchedules = "single_schedules"
	ListSingleSchedulesResponseFieldTotalElements  = "total_elements"
	ListSingleSchedulesResponseFieldHasNext        = "has_next"

	// Fields and Edges constants for "UpdateSingleScheduleRequest"
	UpdateSingleScheduleRequestFieldResourceId    = "resource_id"
	UpdateSingleScheduleRequestEdgeSingleSchedule = "single_schedule"

	// Fields and Edges constants for "PatchSingleScheduleRequest"
	PatchSingleScheduleRequestFieldResourceId    = "resource_id"
	PatchSingleScheduleRequestEdgeSingleSchedule = "single_schedule"
	PatchSingleScheduleRequestEdgeFieldMask      = "field_mask"

	// Fields and Edges constants for "DeleteSingleScheduleRequest"
	DeleteSingleScheduleRequestFieldResourceId = "resource_id"

	// Fields and Edges constants for "DeleteSingleScheduleResponse"

	// Fields and Edges constants for "CreateRepeatedScheduleRequest"
	CreateRepeatedScheduleRequestEdgeRepeatedSchedule = "repeated_schedule"

	// Fields and Edges constants for "CreateRepeatedScheduleResponse"
	CreateRepeatedScheduleResponseEdgeRepeatedSchedule = "repeated_schedule"

	// Fields and Edges constants for "GetRepeatedScheduleRequest"
	GetRepeatedScheduleRequestFieldResourceId = "resource_id"

	// Fields and Edges constants for "GetRepeatedScheduleResponse"
	GetRepeatedScheduleResponseEdgeRepeatedSchedule = "repeated_schedule"

	// Fields and Edges constants for "ListRepeatedSchedulesRequest"
	ListRepeatedSchedulesRequestFieldPageSize  = "page_size"
	ListRepeatedSchedulesRequestFieldOffset    = "offset"
	ListRepeatedSchedulesRequestFieldHostId    = "host_id"
	ListRepeatedSchedulesRequestFieldSiteId    = "site_id"
	ListRepeatedSchedulesRequestFieldRegionId  = "region_id"
	ListRepeatedSchedulesRequestFieldUnixEpoch = "unix_epoch"

	// Fields and Edges constants for "ListRepeatedSchedulesResponse"
	ListRepeatedSchedulesResponseEdgeRepeatedSchedules = "repeated_schedules"
	ListRepeatedSchedulesResponseFieldTotalElements    = "total_elements"
	ListRepeatedSchedulesResponseFieldHasNext          = "has_next"

	// Fields and Edges constants for "UpdateRepeatedScheduleRequest"
	UpdateRepeatedScheduleRequestFieldResourceId      = "resource_id"
	UpdateRepeatedScheduleRequestEdgeRepeatedSchedule = "repeated_schedule"

	// Fields and Edges constants for "PatchRepeatedScheduleRequest"
	PatchRepeatedScheduleRequestFieldResourceId      = "resource_id"
	PatchRepeatedScheduleRequestEdgeRepeatedSchedule = "repeated_schedule"
	PatchRepeatedScheduleRequestEdgeFieldMask        = "field_mask"

	// Fields and Edges constants for "DeleteRepeatedScheduleRequest"
	DeleteRepeatedScheduleRequestFieldResourceId = "resource_id"

	// Fields and Edges constants for "DeleteRepeatedScheduleResponse"

	// Fields and Edges constants for "CreateTelemetryLogsGroupRequest"
	CreateTelemetryLogsGroupRequestEdgeTelemetryLogsGroup = "telemetry_logs_group"

	// Fields and Edges constants for "CreateTelemetryLogsGroupResponse"
	CreateTelemetryLogsGroupResponseEdgeTelemetryLogsGroup = "telemetry_logs_group"

	// Fields and Edges constants for "GetTelemetryLogsGroupRequest"
	GetTelemetryLogsGroupRequestFieldResourceId = "resource_id"

	// Fields and Edges constants for "GetTelemetryLogsGroupResponse"
	GetTelemetryLogsGroupResponseEdgeTelemetryLogsGroup = "telemetry_logs_group"

	// Fields and Edges constants for "ListTelemetryLogsGroupsRequest"
	ListTelemetryLogsGroupsRequestFieldPageSize = "page_size"
	ListTelemetryLogsGroupsRequestFieldOffset   = "offset"
	ListTelemetryLogsGroupsRequestFieldOrderBy  = "order_by"

	// Fields and Edges constants for "ListTelemetryLogsGroupsResponse"
	ListTelemetryLogsGroupsResponseEdgeTelemetryLogsGroups = "telemetry_logs_groups"
	ListTelemetryLogsGroupsResponseFieldTotalElements      = "total_elements"
	ListTelemetryLogsGroupsResponseFieldHasNext            = "has_next"

	// Fields and Edges constants for "DeleteTelemetryLogsGroupRequest"
	DeleteTelemetryLogsGroupRequestFieldResourceId = "resource_id"

	// Fields and Edges constants for "DeleteTelemetryLogsGroupResponse"

	// Fields and Edges constants for "CreateTelemetryMetricsGroupRequest"
	CreateTelemetryMetricsGroupRequestEdgeTelemetryMetricsGroup = "telemetry_metrics_group"

	// Fields and Edges constants for "CreateTelemetryMetricsGroupResponse"
	CreateTelemetryMetricsGroupResponseEdgeTelemetryMetricsGroup = "telemetry_metrics_group"

	// Fields and Edges constants for "GetTelemetryMetricsGroupRequest"
	GetTelemetryMetricsGroupRequestFieldResourceId = "resource_id"

	// Fields and Edges constants for "GetTelemetryMetricsGroupResponse"
	GetTelemetryMetricsGroupResponseEdgeTelemetryMetricsGroup = "telemetry_metrics_group"

	// Fields and Edges constants for "ListTelemetryMetricsGroupsRequest"
	ListTelemetryMetricsGroupsRequestFieldPageSize = "page_size"
	ListTelemetryMetricsGroupsRequestFieldOffset   = "offset"
	ListTelemetryMetricsGroupsRequestFieldOrderBy  = "order_by"

	// Fields and Edges constants for "ListTelemetryMetricsGroupsResponse"
	ListTelemetryMetricsGroupsResponseEdgeTelemetryMetricsGroups = "telemetry_metrics_groups"
	ListTelemetryMetricsGroupsResponseFieldTotalElements         = "total_elements"
	ListTelemetryMetricsGroupsResponseFieldHasNext               = "has_next"

	// Fields and Edges constants for "DeleteTelemetryMetricsGroupRequest"
	DeleteTelemetryMetricsGroupRequestFieldResourceId = "resource_id"

	// Fields and Edges constants for "DeleteTelemetryMetricsGroupResponse"

	// Fields and Edges constants for "CreateTelemetryLogsProfileRequest"
	CreateTelemetryLogsProfileRequestEdgeTelemetryLogsProfile = "telemetry_logs_profile"

	// Fields and Edges constants for "CreateTelemetryLogsProfileResponse"
	CreateTelemetryLogsProfileResponseEdgeTelemetryLogsProfile = "telemetry_logs_profile"

	// Fields and Edges constants for "GetTelemetryLogsProfileRequest"
	GetTelemetryLogsProfileRequestFieldResourceId = "resource_id"

	// Fields and Edges constants for "GetTelemetryLogsProfileResponse"
	GetTelemetryLogsProfileResponseEdgeTelemetryLogsProfile = "telemetry_logs_profile"

	// Fields and Edges constants for "ListTelemetryLogsProfilesRequest"
	ListTelemetryLogsProfilesRequestFieldPageSize      = "page_size"
	ListTelemetryLogsProfilesRequestFieldOffset        = "offset"
	ListTelemetryLogsProfilesRequestFieldOrderBy       = "order_by"
	ListTelemetryLogsProfilesRequestFieldInstanceId    = "instance_id"
	ListTelemetryLogsProfilesRequestFieldSiteId        = "site_id"
	ListTelemetryLogsProfilesRequestFieldRegionId      = "region_id"
	ListTelemetryLogsProfilesRequestFieldShowInherited = "show_inherited"

	// Fields and Edges constants for "ListTelemetryLogsProfilesResponse"
	ListTelemetryLogsProfilesResponseEdgeTelemetryLogsProfiles = "telemetry_logs_profiles"
	ListTelemetryLogsProfilesResponseFieldTotalElements        = "total_elements"
	ListTelemetryLogsProfilesResponseFieldHasNext              = "has_next"

	// Fields and Edges constants for "UpdateTelemetryLogsProfileRequest"
	UpdateTelemetryLogsProfileRequestFieldResourceId          = "resource_id"
	UpdateTelemetryLogsProfileRequestEdgeTelemetryLogsProfile = "telemetry_logs_profile"

	// Fields and Edges constants for "PatchTelemetryLogsProfileRequest"
	PatchTelemetryLogsProfileRequestFieldResourceId          = "resource_id"
	PatchTelemetryLogsProfileRequestEdgeTelemetryLogsProfile = "telemetry_logs_profile"
	PatchTelemetryLogsProfileRequestEdgeFieldMask            = "field_mask"

	// Fields and Edges constants for "DeleteTelemetryLogsProfileRequest"
	DeleteTelemetryLogsProfileRequestFieldResourceId = "resource_id"

	// Fields and Edges constants for "DeleteTelemetryLogsProfileResponse"

	// Fields and Edges constants for "CreateTelemetryMetricsProfileRequest"
	CreateTelemetryMetricsProfileRequestEdgeTelemetryMetricsProfile = "telemetry_metrics_profile"

	// Fields and Edges constants for "CreateTelemetryMetricsProfileResponse"
	CreateTelemetryMetricsProfileResponseEdgeTelemetryMetricsProfile = "telemetry_metrics_profile"

	// Fields and Edges constants for "GetTelemetryMetricsProfileRequest"
	GetTelemetryMetricsProfileRequestFieldResourceId = "resource_id"

	// Fields and Edges constants for "GetTelemetryMetricsProfileResponse"
	GetTelemetryMetricsProfileResponseEdgeTelemetryMetricsProfile = "telemetry_metrics_profile"

	// Fields and Edges constants for "ListTelemetryMetricsProfilesRequest"
	ListTelemetryMetricsProfilesRequestFieldPageSize      = "page_size"
	ListTelemetryMetricsProfilesRequestFieldOffset        = "offset"
	ListTelemetryMetricsProfilesRequestFieldOrderBy       = "order_by"
	ListTelemetryMetricsProfilesRequestFieldInstanceId    = "instance_id"
	ListTelemetryMetricsProfilesRequestFieldSiteId        = "site_id"
	ListTelemetryMetricsProfilesRequestFieldRegionId      = "region_id"
	ListTelemetryMetricsProfilesRequestFieldShowInherited = "show_inherited"

	// Fields and Edges constants for "ListTelemetryMetricsProfilesResponse"
	ListTelemetryMetricsProfilesResponseEdgeTelemetryMetricsProfiles = "telemetry_metrics_profiles"
	ListTelemetryMetricsProfilesResponseFieldTotalElements           = "total_elements"
	ListTelemetryMetricsProfilesResponseFieldHasNext                 = "has_next"

	// Fields and Edges constants for "UpdateTelemetryMetricsProfileRequest"
	UpdateTelemetryMetricsProfileRequestFieldResourceId             = "resource_id"
	UpdateTelemetryMetricsProfileRequestEdgeTelemetryMetricsProfile = "telemetry_metrics_profile"

	// Fields and Edges constants for "PatchTelemetryMetricsProfileRequest"
	PatchTelemetryMetricsProfileRequestFieldResourceId             = "resource_id"
	PatchTelemetryMetricsProfileRequestEdgeTelemetryMetricsProfile = "telemetry_metrics_profile"
	PatchTelemetryMetricsProfileRequestEdgeFieldMask               = "field_mask"

	// Fields and Edges constants for "DeleteTelemetryMetricsProfileRequest"
	DeleteTelemetryMetricsProfileRequestFieldResourceId = "resource_id"

	// Fields and Edges constants for "DeleteTelemetryMetricsProfileResponse"

	// Fields and Edges constants for "CreateLocalAccountRequest"
	CreateLocalAccountRequestEdgeLocalAccount = "local_account"

	// Fields and Edges constants for "CreateLocalAccountResponse"
	CreateLocalAccountResponseEdgeLocalAccount = "local_account"

	// Fields and Edges constants for "GetLocalAccountRequest"
	GetLocalAccountRequestFieldResourceId = "resource_id"

	// Fields and Edges constants for "GetLocalAccountResponse"
	GetLocalAccountResponseEdgeLocalAccount = "local_account"

	// Fields and Edges constants for "ListLocalAccountsRequest"
	ListLocalAccountsRequestFieldOrderBy  = "order_by"
	ListLocalAccountsRequestFieldFilter   = "filter"
	ListLocalAccountsRequestFieldPageSize = "page_size"
	ListLocalAccountsRequestFieldOffset   = "offset"

	// Fields and Edges constants for "ListLocalAccountsResponse"
	ListLocalAccountsResponseEdgeLocalAccounts  = "local_accounts"
	ListLocalAccountsResponseFieldTotalElements = "total_elements"
	ListLocalAccountsResponseFieldHasNext       = "has_next"

	// Fields and Edges constants for "DeleteLocalAccountRequest"
	DeleteLocalAccountRequestFieldResourceId = "resource_id"

	// Fields and Edges constants for "DeleteLocalAccountResponse"

	// Fields and Edges constants for "CreateOSUpdatePolicyRequest"
	CreateOSUpdatePolicyRequestEdgeOsUpdatePolicy = "os_update_policy"

	// Fields and Edges constants for "CreateOSUpdatePolicyResponse"
	CreateOSUpdatePolicyResponseEdgeOsUpdatePolicy = "os_update_policy"

	// Fields and Edges constants for "GetOSUpdatePolicyRequest"
	GetOSUpdatePolicyRequestFieldResourceId = "resource_id"

	// Fields and Edges constants for "GetOSUpdatePolicyResponse"
	GetOSUpdatePolicyResponseEdgeOsUpdatePolicy = "os_update_policy"

	// Fields and Edges constants for "ListOSUpdatePolicyRequest"
	ListOSUpdatePolicyRequestFieldOrderBy  = "order_by"
	ListOSUpdatePolicyRequestFieldFilter   = "filter"
	ListOSUpdatePolicyRequestFieldPageSize = "page_size"
	ListOSUpdatePolicyRequestFieldOffset   = "offset"

	// Fields and Edges constants for "ListOSUpdatePolicyResponse"
	ListOSUpdatePolicyResponseEdgeOsUpdatePolicies = "os_update_policies"
	ListOSUpdatePolicyResponseFieldTotalElements   = "total_elements"
	ListOSUpdatePolicyResponseFieldHasNext         = "has_next"

	// Fields and Edges constants for "DeleteOSUpdatePolicyRequest"
	DeleteOSUpdatePolicyRequestFieldResourceId = "resource_id"

// Fields and Edges constants for "DeleteOSUpdatePolicyResponse"

)
