// Code generated by protoc-gen-go-const. DO NOT EDIT.

// source: resources/location/v1/location.proto

package locationv1

const (
	// Fields and Edges constants for "RegionResource"
	RegionResourceFieldResourceId       = "resource_id"
	RegionResourceFieldName             = "name"
	RegionResourceEdgeParentRegion      = "parent_region"
	RegionResourceFieldRegionID         = "regionID"
	RegionResourceEdgeMetadata          = "metadata"
	RegionResourceEdgeInheritedMetadata = "inherited_metadata"
	RegionResourceFieldTotalSites       = "total_sites"
	RegionResourceFieldParentId         = "parent_id"
	RegionResourceEdgeTimestamps        = "timestamps"

	// Fields and Edges constants for "SiteResource"
	SiteResourceFieldResourceId       = "resource_id"
	SiteResourceFieldName             = "name"
	SiteResourceEdgeRegion            = "region"
	SiteResourceFieldSiteLat          = "site_lat"
	SiteResourceFieldSiteLng          = "site_lng"
	SiteResourceEdgeProvider          = "provider"
	SiteResourceFieldSiteID           = "siteID"
	SiteResourceEdgeMetadata          = "metadata"
	SiteResourceEdgeInheritedMetadata = "inherited_metadata"
	SiteResourceFieldRegionId         = "region_id"
	SiteResourceEdgeTimestamps        = "timestamps"
)
