// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/open-edge-platform/infra-core/inventory/v2/internal/ent/hostresource"
	"github.com/open-edge-platform/infra-core/inventory/v2/internal/ent/hoststorageresource"
)

// HoststorageResourceCreate is the builder for creating a HoststorageResource entity.
type HoststorageResourceCreate struct {
	config
	mutation *HoststorageResourceMutation
	hooks    []Hook
}

// SetResourceID sets the "resource_id" field.
func (_c *HoststorageResourceCreate) SetResourceID(v string) *HoststorageResourceCreate {
	_c.mutation.SetResourceID(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *HoststorageResourceCreate) SetKind(v string) *HoststorageResourceCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_c *HoststorageResourceCreate) SetNillableKind(v *string) *HoststorageResourceCreate {
	if v != nil {
		_c.SetKind(*v)
	}
	return _c
}

// SetProviderStatus sets the "provider_status" field.
func (_c *HoststorageResourceCreate) SetProviderStatus(v string) *HoststorageResourceCreate {
	_c.mutation.SetProviderStatus(v)
	return _c
}

// SetNillableProviderStatus sets the "provider_status" field if the given value is not nil.
func (_c *HoststorageResourceCreate) SetNillableProviderStatus(v *string) *HoststorageResourceCreate {
	if v != nil {
		_c.SetProviderStatus(*v)
	}
	return _c
}

// SetWwid sets the "wwid" field.
func (_c *HoststorageResourceCreate) SetWwid(v string) *HoststorageResourceCreate {
	_c.mutation.SetWwid(v)
	return _c
}

// SetNillableWwid sets the "wwid" field if the given value is not nil.
func (_c *HoststorageResourceCreate) SetNillableWwid(v *string) *HoststorageResourceCreate {
	if v != nil {
		_c.SetWwid(*v)
	}
	return _c
}

// SetSerial sets the "serial" field.
func (_c *HoststorageResourceCreate) SetSerial(v string) *HoststorageResourceCreate {
	_c.mutation.SetSerial(v)
	return _c
}

// SetNillableSerial sets the "serial" field if the given value is not nil.
func (_c *HoststorageResourceCreate) SetNillableSerial(v *string) *HoststorageResourceCreate {
	if v != nil {
		_c.SetSerial(*v)
	}
	return _c
}

// SetVendor sets the "vendor" field.
func (_c *HoststorageResourceCreate) SetVendor(v string) *HoststorageResourceCreate {
	_c.mutation.SetVendor(v)
	return _c
}

// SetNillableVendor sets the "vendor" field if the given value is not nil.
func (_c *HoststorageResourceCreate) SetNillableVendor(v *string) *HoststorageResourceCreate {
	if v != nil {
		_c.SetVendor(*v)
	}
	return _c
}

// SetModel sets the "model" field.
func (_c *HoststorageResourceCreate) SetModel(v string) *HoststorageResourceCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *HoststorageResourceCreate) SetNillableModel(v *string) *HoststorageResourceCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetCapacityBytes sets the "capacity_bytes" field.
func (_c *HoststorageResourceCreate) SetCapacityBytes(v uint64) *HoststorageResourceCreate {
	_c.mutation.SetCapacityBytes(v)
	return _c
}

// SetNillableCapacityBytes sets the "capacity_bytes" field if the given value is not nil.
func (_c *HoststorageResourceCreate) SetNillableCapacityBytes(v *uint64) *HoststorageResourceCreate {
	if v != nil {
		_c.SetCapacityBytes(*v)
	}
	return _c
}

// SetDeviceName sets the "device_name" field.
func (_c *HoststorageResourceCreate) SetDeviceName(v string) *HoststorageResourceCreate {
	_c.mutation.SetDeviceName(v)
	return _c
}

// SetNillableDeviceName sets the "device_name" field if the given value is not nil.
func (_c *HoststorageResourceCreate) SetNillableDeviceName(v *string) *HoststorageResourceCreate {
	if v != nil {
		_c.SetDeviceName(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *HoststorageResourceCreate) SetTenantID(v string) *HoststorageResourceCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *HoststorageResourceCreate) SetCreatedAt(v string) *HoststorageResourceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *HoststorageResourceCreate) SetUpdatedAt(v string) *HoststorageResourceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetHostID sets the "host" edge to the HostResource entity by ID.
func (_c *HoststorageResourceCreate) SetHostID(id int) *HoststorageResourceCreate {
	_c.mutation.SetHostID(id)
	return _c
}

// SetHost sets the "host" edge to the HostResource entity.
func (_c *HoststorageResourceCreate) SetHost(v *HostResource) *HoststorageResourceCreate {
	return _c.SetHostID(v.ID)
}

// Mutation returns the HoststorageResourceMutation object of the builder.
func (_c *HoststorageResourceCreate) Mutation() *HoststorageResourceMutation {
	return _c.mutation
}

// Save creates the HoststorageResource in the database.
func (_c *HoststorageResourceCreate) Save(ctx context.Context) (*HoststorageResource, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *HoststorageResourceCreate) SaveX(ctx context.Context) *HoststorageResource {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HoststorageResourceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HoststorageResourceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *HoststorageResourceCreate) check() error {
	if _, ok := _c.mutation.ResourceID(); !ok {
		return &ValidationError{Name: "resource_id", err: errors.New(`ent: missing required field "HoststorageResource.resource_id"`)}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "HoststorageResource.tenant_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "HoststorageResource.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "HoststorageResource.updated_at"`)}
	}
	if len(_c.mutation.HostIDs()) == 0 {
		return &ValidationError{Name: "host", err: errors.New(`ent: missing required edge "HoststorageResource.host"`)}
	}
	return nil
}

func (_c *HoststorageResourceCreate) sqlSave(ctx context.Context) (*HoststorageResource, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *HoststorageResourceCreate) createSpec() (*HoststorageResource, *sqlgraph.CreateSpec) {
	var (
		_node = &HoststorageResource{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(hoststorageresource.Table, sqlgraph.NewFieldSpec(hoststorageresource.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.ResourceID(); ok {
		_spec.SetField(hoststorageresource.FieldResourceID, field.TypeString, value)
		_node.ResourceID = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(hoststorageresource.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.ProviderStatus(); ok {
		_spec.SetField(hoststorageresource.FieldProviderStatus, field.TypeString, value)
		_node.ProviderStatus = value
	}
	if value, ok := _c.mutation.Wwid(); ok {
		_spec.SetField(hoststorageresource.FieldWwid, field.TypeString, value)
		_node.Wwid = value
	}
	if value, ok := _c.mutation.Serial(); ok {
		_spec.SetField(hoststorageresource.FieldSerial, field.TypeString, value)
		_node.Serial = value
	}
	if value, ok := _c.mutation.Vendor(); ok {
		_spec.SetField(hoststorageresource.FieldVendor, field.TypeString, value)
		_node.Vendor = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(hoststorageresource.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.CapacityBytes(); ok {
		_spec.SetField(hoststorageresource.FieldCapacityBytes, field.TypeUint64, value)
		_node.CapacityBytes = value
	}
	if value, ok := _c.mutation.DeviceName(); ok {
		_spec.SetField(hoststorageresource.FieldDeviceName, field.TypeString, value)
		_node.DeviceName = value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(hoststorageresource.FieldTenantID, field.TypeString, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(hoststorageresource.FieldCreatedAt, field.TypeString, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(hoststorageresource.FieldUpdatedAt, field.TypeString, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.HostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   hoststorageresource.HostTable,
			Columns: []string{hoststorageresource.HostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hostresource.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.hoststorage_resource_host = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// HoststorageResourceCreateBulk is the builder for creating many HoststorageResource entities in bulk.
type HoststorageResourceCreateBulk struct {
	config
	err      error
	builders []*HoststorageResourceCreate
}

// Save creates the HoststorageResource entities in the database.
func (_c *HoststorageResourceCreateBulk) Save(ctx context.Context) ([]*HoststorageResource, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*HoststorageResource, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HoststorageResourceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *HoststorageResourceCreateBulk) SaveX(ctx context.Context) []*HoststorageResource {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HoststorageResourceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HoststorageResourceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
