// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/open-edge-platform/infra-core/inventory/v2/internal/ent/hostdeviceresource"
	"github.com/open-edge-platform/infra-core/inventory/v2/internal/ent/hostresource"
)

// HostdeviceResourceCreate is the builder for creating a HostdeviceResource entity.
type HostdeviceResourceCreate struct {
	config
	mutation *HostdeviceResourceMutation
	hooks    []Hook
}

// SetResourceID sets the "resource_id" field.
func (_c *HostdeviceResourceCreate) SetResourceID(v string) *HostdeviceResourceCreate {
	_c.mutation.SetResourceID(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *HostdeviceResourceCreate) SetKind(v string) *HostdeviceResourceCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_c *HostdeviceResourceCreate) SetNillableKind(v *string) *HostdeviceResourceCreate {
	if v != nil {
		_c.SetKind(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *HostdeviceResourceCreate) SetVersion(v string) *HostdeviceResourceCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *HostdeviceResourceCreate) SetNillableVersion(v *string) *HostdeviceResourceCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetDeviceName sets the "device_name" field.
func (_c *HostdeviceResourceCreate) SetDeviceName(v string) *HostdeviceResourceCreate {
	_c.mutation.SetDeviceName(v)
	return _c
}

// SetNillableDeviceName sets the "device_name" field if the given value is not nil.
func (_c *HostdeviceResourceCreate) SetNillableDeviceName(v *string) *HostdeviceResourceCreate {
	if v != nil {
		_c.SetDeviceName(*v)
	}
	return _c
}

// SetOperationalState sets the "operational_state" field.
func (_c *HostdeviceResourceCreate) SetOperationalState(v string) *HostdeviceResourceCreate {
	_c.mutation.SetOperationalState(v)
	return _c
}

// SetNillableOperationalState sets the "operational_state" field if the given value is not nil.
func (_c *HostdeviceResourceCreate) SetNillableOperationalState(v *string) *HostdeviceResourceCreate {
	if v != nil {
		_c.SetOperationalState(*v)
	}
	return _c
}

// SetBuildNumber sets the "build_number" field.
func (_c *HostdeviceResourceCreate) SetBuildNumber(v string) *HostdeviceResourceCreate {
	_c.mutation.SetBuildNumber(v)
	return _c
}

// SetNillableBuildNumber sets the "build_number" field if the given value is not nil.
func (_c *HostdeviceResourceCreate) SetNillableBuildNumber(v *string) *HostdeviceResourceCreate {
	if v != nil {
		_c.SetBuildNumber(*v)
	}
	return _c
}

// SetSku sets the "sku" field.
func (_c *HostdeviceResourceCreate) SetSku(v string) *HostdeviceResourceCreate {
	_c.mutation.SetSku(v)
	return _c
}

// SetNillableSku sets the "sku" field if the given value is not nil.
func (_c *HostdeviceResourceCreate) SetNillableSku(v *string) *HostdeviceResourceCreate {
	if v != nil {
		_c.SetSku(*v)
	}
	return _c
}

// SetFeatures sets the "features" field.
func (_c *HostdeviceResourceCreate) SetFeatures(v string) *HostdeviceResourceCreate {
	_c.mutation.SetFeatures(v)
	return _c
}

// SetNillableFeatures sets the "features" field if the given value is not nil.
func (_c *HostdeviceResourceCreate) SetNillableFeatures(v *string) *HostdeviceResourceCreate {
	if v != nil {
		_c.SetFeatures(*v)
	}
	return _c
}

// SetDeviceGUID sets the "device_guid" field.
func (_c *HostdeviceResourceCreate) SetDeviceGUID(v string) *HostdeviceResourceCreate {
	_c.mutation.SetDeviceGUID(v)
	return _c
}

// SetNillableDeviceGUID sets the "device_guid" field if the given value is not nil.
func (_c *HostdeviceResourceCreate) SetNillableDeviceGUID(v *string) *HostdeviceResourceCreate {
	if v != nil {
		_c.SetDeviceGUID(*v)
	}
	return _c
}

// SetControlMode sets the "control_mode" field.
func (_c *HostdeviceResourceCreate) SetControlMode(v string) *HostdeviceResourceCreate {
	_c.mutation.SetControlMode(v)
	return _c
}

// SetNillableControlMode sets the "control_mode" field if the given value is not nil.
func (_c *HostdeviceResourceCreate) SetNillableControlMode(v *string) *HostdeviceResourceCreate {
	if v != nil {
		_c.SetControlMode(*v)
	}
	return _c
}

// SetDNSSuffix sets the "dns_suffix" field.
func (_c *HostdeviceResourceCreate) SetDNSSuffix(v string) *HostdeviceResourceCreate {
	_c.mutation.SetDNSSuffix(v)
	return _c
}

// SetNillableDNSSuffix sets the "dns_suffix" field if the given value is not nil.
func (_c *HostdeviceResourceCreate) SetNillableDNSSuffix(v *string) *HostdeviceResourceCreate {
	if v != nil {
		_c.SetDNSSuffix(*v)
	}
	return _c
}

// SetNetworkStatus sets the "network_status" field.
func (_c *HostdeviceResourceCreate) SetNetworkStatus(v string) *HostdeviceResourceCreate {
	_c.mutation.SetNetworkStatus(v)
	return _c
}

// SetNillableNetworkStatus sets the "network_status" field if the given value is not nil.
func (_c *HostdeviceResourceCreate) SetNillableNetworkStatus(v *string) *HostdeviceResourceCreate {
	if v != nil {
		_c.SetNetworkStatus(*v)
	}
	return _c
}

// SetRemoteStatus sets the "remote_status" field.
func (_c *HostdeviceResourceCreate) SetRemoteStatus(v string) *HostdeviceResourceCreate {
	_c.mutation.SetRemoteStatus(v)
	return _c
}

// SetNillableRemoteStatus sets the "remote_status" field if the given value is not nil.
func (_c *HostdeviceResourceCreate) SetNillableRemoteStatus(v *string) *HostdeviceResourceCreate {
	if v != nil {
		_c.SetRemoteStatus(*v)
	}
	return _c
}

// SetRemoteTrigger sets the "remote_trigger" field.
func (_c *HostdeviceResourceCreate) SetRemoteTrigger(v string) *HostdeviceResourceCreate {
	_c.mutation.SetRemoteTrigger(v)
	return _c
}

// SetNillableRemoteTrigger sets the "remote_trigger" field if the given value is not nil.
func (_c *HostdeviceResourceCreate) SetNillableRemoteTrigger(v *string) *HostdeviceResourceCreate {
	if v != nil {
		_c.SetRemoteTrigger(*v)
	}
	return _c
}

// SetMpsHostname sets the "mps_hostname" field.
func (_c *HostdeviceResourceCreate) SetMpsHostname(v string) *HostdeviceResourceCreate {
	_c.mutation.SetMpsHostname(v)
	return _c
}

// SetNillableMpsHostname sets the "mps_hostname" field if the given value is not nil.
func (_c *HostdeviceResourceCreate) SetNillableMpsHostname(v *string) *HostdeviceResourceCreate {
	if v != nil {
		_c.SetMpsHostname(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *HostdeviceResourceCreate) SetTenantID(v string) *HostdeviceResourceCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *HostdeviceResourceCreate) SetCreatedAt(v string) *HostdeviceResourceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *HostdeviceResourceCreate) SetUpdatedAt(v string) *HostdeviceResourceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetHostID sets the "host" edge to the HostResource entity by ID.
func (_c *HostdeviceResourceCreate) SetHostID(id int) *HostdeviceResourceCreate {
	_c.mutation.SetHostID(id)
	return _c
}

// SetHost sets the "host" edge to the HostResource entity.
func (_c *HostdeviceResourceCreate) SetHost(v *HostResource) *HostdeviceResourceCreate {
	return _c.SetHostID(v.ID)
}

// Mutation returns the HostdeviceResourceMutation object of the builder.
func (_c *HostdeviceResourceCreate) Mutation() *HostdeviceResourceMutation {
	return _c.mutation
}

// Save creates the HostdeviceResource in the database.
func (_c *HostdeviceResourceCreate) Save(ctx context.Context) (*HostdeviceResource, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *HostdeviceResourceCreate) SaveX(ctx context.Context) *HostdeviceResource {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HostdeviceResourceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HostdeviceResourceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *HostdeviceResourceCreate) check() error {
	if _, ok := _c.mutation.ResourceID(); !ok {
		return &ValidationError{Name: "resource_id", err: errors.New(`ent: missing required field "HostdeviceResource.resource_id"`)}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "HostdeviceResource.tenant_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "HostdeviceResource.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "HostdeviceResource.updated_at"`)}
	}
	if len(_c.mutation.HostIDs()) == 0 {
		return &ValidationError{Name: "host", err: errors.New(`ent: missing required edge "HostdeviceResource.host"`)}
	}
	return nil
}

func (_c *HostdeviceResourceCreate) sqlSave(ctx context.Context) (*HostdeviceResource, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *HostdeviceResourceCreate) createSpec() (*HostdeviceResource, *sqlgraph.CreateSpec) {
	var (
		_node = &HostdeviceResource{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(hostdeviceresource.Table, sqlgraph.NewFieldSpec(hostdeviceresource.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.ResourceID(); ok {
		_spec.SetField(hostdeviceresource.FieldResourceID, field.TypeString, value)
		_node.ResourceID = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(hostdeviceresource.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(hostdeviceresource.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.DeviceName(); ok {
		_spec.SetField(hostdeviceresource.FieldDeviceName, field.TypeString, value)
		_node.DeviceName = value
	}
	if value, ok := _c.mutation.OperationalState(); ok {
		_spec.SetField(hostdeviceresource.FieldOperationalState, field.TypeString, value)
		_node.OperationalState = value
	}
	if value, ok := _c.mutation.BuildNumber(); ok {
		_spec.SetField(hostdeviceresource.FieldBuildNumber, field.TypeString, value)
		_node.BuildNumber = value
	}
	if value, ok := _c.mutation.Sku(); ok {
		_spec.SetField(hostdeviceresource.FieldSku, field.TypeString, value)
		_node.Sku = value
	}
	if value, ok := _c.mutation.Features(); ok {
		_spec.SetField(hostdeviceresource.FieldFeatures, field.TypeString, value)
		_node.Features = value
	}
	if value, ok := _c.mutation.DeviceGUID(); ok {
		_spec.SetField(hostdeviceresource.FieldDeviceGUID, field.TypeString, value)
		_node.DeviceGUID = value
	}
	if value, ok := _c.mutation.ControlMode(); ok {
		_spec.SetField(hostdeviceresource.FieldControlMode, field.TypeString, value)
		_node.ControlMode = value
	}
	if value, ok := _c.mutation.DNSSuffix(); ok {
		_spec.SetField(hostdeviceresource.FieldDNSSuffix, field.TypeString, value)
		_node.DNSSuffix = value
	}
	if value, ok := _c.mutation.NetworkStatus(); ok {
		_spec.SetField(hostdeviceresource.FieldNetworkStatus, field.TypeString, value)
		_node.NetworkStatus = value
	}
	if value, ok := _c.mutation.RemoteStatus(); ok {
		_spec.SetField(hostdeviceresource.FieldRemoteStatus, field.TypeString, value)
		_node.RemoteStatus = value
	}
	if value, ok := _c.mutation.RemoteTrigger(); ok {
		_spec.SetField(hostdeviceresource.FieldRemoteTrigger, field.TypeString, value)
		_node.RemoteTrigger = value
	}
	if value, ok := _c.mutation.MpsHostname(); ok {
		_spec.SetField(hostdeviceresource.FieldMpsHostname, field.TypeString, value)
		_node.MpsHostname = value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(hostdeviceresource.FieldTenantID, field.TypeString, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(hostdeviceresource.FieldCreatedAt, field.TypeString, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(hostdeviceresource.FieldUpdatedAt, field.TypeString, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.HostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   hostdeviceresource.HostTable,
			Columns: []string{hostdeviceresource.HostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hostresource.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.hostdevice_resource_host = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// HostdeviceResourceCreateBulk is the builder for creating many HostdeviceResource entities in bulk.
type HostdeviceResourceCreateBulk struct {
	config
	err      error
	builders []*HostdeviceResourceCreate
}

// Save creates the HostdeviceResource entities in the database.
func (_c *HostdeviceResourceCreateBulk) Save(ctx context.Context) ([]*HostdeviceResource, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*HostdeviceResource, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HostdeviceResourceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *HostdeviceResourceCreateBulk) SaveX(ctx context.Context) []*HostdeviceResource {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HostdeviceResourceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HostdeviceResourceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
