// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/open-edge-platform/infra-core/inventory/v2/internal/ent/hostamtconfigresource"
	"github.com/open-edge-platform/infra-core/inventory/v2/internal/ent/hostresource"
	"github.com/open-edge-platform/infra-core/inventory/v2/internal/ent/predicate"
)

// HostamtconfigResourceQuery is the builder for querying HostamtconfigResource entities.
type HostamtconfigResourceQuery struct {
	config
	ctx        *QueryContext
	order      []hostamtconfigresource.OrderOption
	inters     []Interceptor
	predicates []predicate.HostamtconfigResource
	withHost   *HostResourceQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the HostamtconfigResourceQuery builder.
func (_q *HostamtconfigResourceQuery) Where(ps ...predicate.HostamtconfigResource) *HostamtconfigResourceQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *HostamtconfigResourceQuery) Limit(limit int) *HostamtconfigResourceQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *HostamtconfigResourceQuery) Offset(offset int) *HostamtconfigResourceQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *HostamtconfigResourceQuery) Unique(unique bool) *HostamtconfigResourceQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *HostamtconfigResourceQuery) Order(o ...hostamtconfigresource.OrderOption) *HostamtconfigResourceQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryHost chains the current query on the "host" edge.
func (_q *HostamtconfigResourceQuery) QueryHost() *HostResourceQuery {
	query := (&HostResourceClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(hostamtconfigresource.Table, hostamtconfigresource.FieldID, selector),
			sqlgraph.To(hostresource.Table, hostresource.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, hostamtconfigresource.HostTable, hostamtconfigresource.HostColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first HostamtconfigResource entity from the query.
// Returns a *NotFoundError when no HostamtconfigResource was found.
func (_q *HostamtconfigResourceQuery) First(ctx context.Context) (*HostamtconfigResource, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{hostamtconfigresource.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *HostamtconfigResourceQuery) FirstX(ctx context.Context) *HostamtconfigResource {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first HostamtconfigResource ID from the query.
// Returns a *NotFoundError when no HostamtconfigResource ID was found.
func (_q *HostamtconfigResourceQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{hostamtconfigresource.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *HostamtconfigResourceQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single HostamtconfigResource entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one HostamtconfigResource entity is found.
// Returns a *NotFoundError when no HostamtconfigResource entities are found.
func (_q *HostamtconfigResourceQuery) Only(ctx context.Context) (*HostamtconfigResource, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{hostamtconfigresource.Label}
	default:
		return nil, &NotSingularError{hostamtconfigresource.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *HostamtconfigResourceQuery) OnlyX(ctx context.Context) *HostamtconfigResource {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only HostamtconfigResource ID in the query.
// Returns a *NotSingularError when more than one HostamtconfigResource ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *HostamtconfigResourceQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{hostamtconfigresource.Label}
	default:
		err = &NotSingularError{hostamtconfigresource.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *HostamtconfigResourceQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of HostamtconfigResources.
func (_q *HostamtconfigResourceQuery) All(ctx context.Context) ([]*HostamtconfigResource, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*HostamtconfigResource, *HostamtconfigResourceQuery]()
	return withInterceptors[[]*HostamtconfigResource](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *HostamtconfigResourceQuery) AllX(ctx context.Context) []*HostamtconfigResource {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of HostamtconfigResource IDs.
func (_q *HostamtconfigResourceQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(hostamtconfigresource.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *HostamtconfigResourceQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *HostamtconfigResourceQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*HostamtconfigResourceQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *HostamtconfigResourceQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *HostamtconfigResourceQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *HostamtconfigResourceQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the HostamtconfigResourceQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *HostamtconfigResourceQuery) Clone() *HostamtconfigResourceQuery {
	if _q == nil {
		return nil
	}
	return &HostamtconfigResourceQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]hostamtconfigresource.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.HostamtconfigResource{}, _q.predicates...),
		withHost:   _q.withHost.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithHost tells the query-builder to eager-load the nodes that are connected to
// the "host" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *HostamtconfigResourceQuery) WithHost(opts ...func(*HostResourceQuery)) *HostamtconfigResourceQuery {
	query := (&HostResourceClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withHost = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ResourceID string `json:"resource_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.HostamtconfigResource.Query().
//		GroupBy(hostamtconfigresource.FieldResourceID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *HostamtconfigResourceQuery) GroupBy(field string, fields ...string) *HostamtconfigResourceGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &HostamtconfigResourceGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = hostamtconfigresource.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ResourceID string `json:"resource_id,omitempty"`
//	}
//
//	client.HostamtconfigResource.Query().
//		Select(hostamtconfigresource.FieldResourceID).
//		Scan(ctx, &v)
func (_q *HostamtconfigResourceQuery) Select(fields ...string) *HostamtconfigResourceSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &HostamtconfigResourceSelect{HostamtconfigResourceQuery: _q}
	sbuild.label = hostamtconfigresource.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a HostamtconfigResourceSelect configured with the given aggregations.
func (_q *HostamtconfigResourceQuery) Aggregate(fns ...AggregateFunc) *HostamtconfigResourceSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *HostamtconfigResourceQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !hostamtconfigresource.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *HostamtconfigResourceQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*HostamtconfigResource, error) {
	var (
		nodes       = []*HostamtconfigResource{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withHost != nil,
		}
	)
	if _q.withHost != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, hostamtconfigresource.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*HostamtconfigResource).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &HostamtconfigResource{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withHost; query != nil {
		if err := _q.loadHost(ctx, query, nodes, nil,
			func(n *HostamtconfigResource, e *HostResource) { n.Edges.Host = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *HostamtconfigResourceQuery) loadHost(ctx context.Context, query *HostResourceQuery, nodes []*HostamtconfigResource, init func(*HostamtconfigResource), assign func(*HostamtconfigResource, *HostResource)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*HostamtconfigResource)
	for i := range nodes {
		if nodes[i].hostamtconfig_resource_host == nil {
			continue
		}
		fk := *nodes[i].hostamtconfig_resource_host
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(hostresource.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "hostamtconfig_resource_host" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *HostamtconfigResourceQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *HostamtconfigResourceQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(hostamtconfigresource.Table, hostamtconfigresource.Columns, sqlgraph.NewFieldSpec(hostamtconfigresource.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, hostamtconfigresource.FieldID)
		for i := range fields {
			if fields[i] != hostamtconfigresource.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *HostamtconfigResourceQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(hostamtconfigresource.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = hostamtconfigresource.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// HostamtconfigResourceGroupBy is the group-by builder for HostamtconfigResource entities.
type HostamtconfigResourceGroupBy struct {
	selector
	build *HostamtconfigResourceQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *HostamtconfigResourceGroupBy) Aggregate(fns ...AggregateFunc) *HostamtconfigResourceGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *HostamtconfigResourceGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*HostamtconfigResourceQuery, *HostamtconfigResourceGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *HostamtconfigResourceGroupBy) sqlScan(ctx context.Context, root *HostamtconfigResourceQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// HostamtconfigResourceSelect is the builder for selecting fields of HostamtconfigResource entities.
type HostamtconfigResourceSelect struct {
	*HostamtconfigResourceQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *HostamtconfigResourceSelect) Aggregate(fns ...AggregateFunc) *HostamtconfigResourceSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *HostamtconfigResourceSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*HostamtconfigResourceQuery, *HostamtconfigResourceSelect](ctx, _s.HostamtconfigResourceQuery, _s, _s.inters, v)
}

func (_s *HostamtconfigResourceSelect) sqlScan(ctx context.Context, root *HostamtconfigResourceQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
