// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/open-edge-platform/infra-core/inventory/v2/internal/ent/localaccountresource"
)

// LocalAccountResourceCreate is the builder for creating a LocalAccountResource entity.
type LocalAccountResourceCreate struct {
	config
	mutation *LocalAccountResourceMutation
	hooks    []Hook
}

// SetResourceID sets the "resource_id" field.
func (_c *LocalAccountResourceCreate) SetResourceID(v string) *LocalAccountResourceCreate {
	_c.mutation.SetResourceID(v)
	return _c
}

// SetUsername sets the "username" field.
func (_c *LocalAccountResourceCreate) SetUsername(v string) *LocalAccountResourceCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetSSHKey sets the "ssh_key" field.
func (_c *LocalAccountResourceCreate) SetSSHKey(v string) *LocalAccountResourceCreate {
	_c.mutation.SetSSHKey(v)
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *LocalAccountResourceCreate) SetTenantID(v string) *LocalAccountResourceCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *LocalAccountResourceCreate) SetCreatedAt(v string) *LocalAccountResourceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *LocalAccountResourceCreate) SetUpdatedAt(v string) *LocalAccountResourceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// Mutation returns the LocalAccountResourceMutation object of the builder.
func (_c *LocalAccountResourceCreate) Mutation() *LocalAccountResourceMutation {
	return _c.mutation
}

// Save creates the LocalAccountResource in the database.
func (_c *LocalAccountResourceCreate) Save(ctx context.Context) (*LocalAccountResource, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LocalAccountResourceCreate) SaveX(ctx context.Context) *LocalAccountResource {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LocalAccountResourceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LocalAccountResourceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LocalAccountResourceCreate) check() error {
	if _, ok := _c.mutation.ResourceID(); !ok {
		return &ValidationError{Name: "resource_id", err: errors.New(`ent: missing required field "LocalAccountResource.resource_id"`)}
	}
	if _, ok := _c.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`ent: missing required field "LocalAccountResource.username"`)}
	}
	if _, ok := _c.mutation.SSHKey(); !ok {
		return &ValidationError{Name: "ssh_key", err: errors.New(`ent: missing required field "LocalAccountResource.ssh_key"`)}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "LocalAccountResource.tenant_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "LocalAccountResource.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "LocalAccountResource.updated_at"`)}
	}
	return nil
}

func (_c *LocalAccountResourceCreate) sqlSave(ctx context.Context) (*LocalAccountResource, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LocalAccountResourceCreate) createSpec() (*LocalAccountResource, *sqlgraph.CreateSpec) {
	var (
		_node = &LocalAccountResource{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(localaccountresource.Table, sqlgraph.NewFieldSpec(localaccountresource.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.ResourceID(); ok {
		_spec.SetField(localaccountresource.FieldResourceID, field.TypeString, value)
		_node.ResourceID = value
	}
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(localaccountresource.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := _c.mutation.SSHKey(); ok {
		_spec.SetField(localaccountresource.FieldSSHKey, field.TypeString, value)
		_node.SSHKey = value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(localaccountresource.FieldTenantID, field.TypeString, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(localaccountresource.FieldCreatedAt, field.TypeString, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(localaccountresource.FieldUpdatedAt, field.TypeString, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// LocalAccountResourceCreateBulk is the builder for creating many LocalAccountResource entities in bulk.
type LocalAccountResourceCreateBulk struct {
	config
	err      error
	builders []*LocalAccountResourceCreate
}

// Save creates the LocalAccountResource entities in the database.
func (_c *LocalAccountResourceCreateBulk) Save(ctx context.Context) ([]*LocalAccountResource, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LocalAccountResource, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LocalAccountResourceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LocalAccountResourceCreateBulk) SaveX(ctx context.Context) []*LocalAccountResource {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LocalAccountResourceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LocalAccountResourceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
