// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/open-edge-platform/infra-core/inventory/v2/internal/ent/operatingsystemresource"
	"github.com/open-edge-platform/infra-core/inventory/v2/internal/ent/osupdatepolicy"
	"github.com/open-edge-platform/infra-core/inventory/v2/internal/ent/predicate"
)

// OSUpdatePolicyUpdate is the builder for updating OSUpdatePolicy entities.
type OSUpdatePolicyUpdate struct {
	config
	hooks    []Hook
	mutation *OSUpdatePolicyMutation
}

// Where appends a list predicates to the OSUpdatePolicyUpdate builder.
func (oupu *OSUpdatePolicyUpdate) Where(ps ...predicate.OSUpdatePolicy) *OSUpdatePolicyUpdate {
	oupu.mutation.Where(ps...)
	return oupu
}

// SetResourceID sets the "resource_id" field.
func (oupu *OSUpdatePolicyUpdate) SetResourceID(s string) *OSUpdatePolicyUpdate {
	oupu.mutation.SetResourceID(s)
	return oupu
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (oupu *OSUpdatePolicyUpdate) SetNillableResourceID(s *string) *OSUpdatePolicyUpdate {
	if s != nil {
		oupu.SetResourceID(*s)
	}
	return oupu
}

// SetInstalledPackages sets the "installed_packages" field.
func (oupu *OSUpdatePolicyUpdate) SetInstalledPackages(s string) *OSUpdatePolicyUpdate {
	oupu.mutation.SetInstalledPackages(s)
	return oupu
}

// SetNillableInstalledPackages sets the "installed_packages" field if the given value is not nil.
func (oupu *OSUpdatePolicyUpdate) SetNillableInstalledPackages(s *string) *OSUpdatePolicyUpdate {
	if s != nil {
		oupu.SetInstalledPackages(*s)
	}
	return oupu
}

// ClearInstalledPackages clears the value of the "installed_packages" field.
func (oupu *OSUpdatePolicyUpdate) ClearInstalledPackages() *OSUpdatePolicyUpdate {
	oupu.mutation.ClearInstalledPackages()
	return oupu
}

// SetUpdateSources sets the "update_sources" field.
func (oupu *OSUpdatePolicyUpdate) SetUpdateSources(s string) *OSUpdatePolicyUpdate {
	oupu.mutation.SetUpdateSources(s)
	return oupu
}

// SetNillableUpdateSources sets the "update_sources" field if the given value is not nil.
func (oupu *OSUpdatePolicyUpdate) SetNillableUpdateSources(s *string) *OSUpdatePolicyUpdate {
	if s != nil {
		oupu.SetUpdateSources(*s)
	}
	return oupu
}

// ClearUpdateSources clears the value of the "update_sources" field.
func (oupu *OSUpdatePolicyUpdate) ClearUpdateSources() *OSUpdatePolicyUpdate {
	oupu.mutation.ClearUpdateSources()
	return oupu
}

// SetKernelCommand sets the "kernel_command" field.
func (oupu *OSUpdatePolicyUpdate) SetKernelCommand(s string) *OSUpdatePolicyUpdate {
	oupu.mutation.SetKernelCommand(s)
	return oupu
}

// SetNillableKernelCommand sets the "kernel_command" field if the given value is not nil.
func (oupu *OSUpdatePolicyUpdate) SetNillableKernelCommand(s *string) *OSUpdatePolicyUpdate {
	if s != nil {
		oupu.SetKernelCommand(*s)
	}
	return oupu
}

// ClearKernelCommand clears the value of the "kernel_command" field.
func (oupu *OSUpdatePolicyUpdate) ClearKernelCommand() *OSUpdatePolicyUpdate {
	oupu.mutation.ClearKernelCommand()
	return oupu
}

// SetUpdatePolicy sets the "update_policy" field.
func (oupu *OSUpdatePolicyUpdate) SetUpdatePolicy(op osupdatepolicy.UpdatePolicy) *OSUpdatePolicyUpdate {
	oupu.mutation.SetUpdatePolicy(op)
	return oupu
}

// SetNillableUpdatePolicy sets the "update_policy" field if the given value is not nil.
func (oupu *OSUpdatePolicyUpdate) SetNillableUpdatePolicy(op *osupdatepolicy.UpdatePolicy) *OSUpdatePolicyUpdate {
	if op != nil {
		oupu.SetUpdatePolicy(*op)
	}
	return oupu
}

// ClearUpdatePolicy clears the value of the "update_policy" field.
func (oupu *OSUpdatePolicyUpdate) ClearUpdatePolicy() *OSUpdatePolicyUpdate {
	oupu.mutation.ClearUpdatePolicy()
	return oupu
}

// SetUpdatedAt sets the "updated_at" field.
func (oupu *OSUpdatePolicyUpdate) SetUpdatedAt(s string) *OSUpdatePolicyUpdate {
	oupu.mutation.SetUpdatedAt(s)
	return oupu
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (oupu *OSUpdatePolicyUpdate) SetNillableUpdatedAt(s *string) *OSUpdatePolicyUpdate {
	if s != nil {
		oupu.SetUpdatedAt(*s)
	}
	return oupu
}

// SetTargetOsID sets the "target_os" edge to the OperatingSystemResource entity by ID.
func (oupu *OSUpdatePolicyUpdate) SetTargetOsID(id int) *OSUpdatePolicyUpdate {
	oupu.mutation.SetTargetOsID(id)
	return oupu
}

// SetNillableTargetOsID sets the "target_os" edge to the OperatingSystemResource entity by ID if the given value is not nil.
func (oupu *OSUpdatePolicyUpdate) SetNillableTargetOsID(id *int) *OSUpdatePolicyUpdate {
	if id != nil {
		oupu = oupu.SetTargetOsID(*id)
	}
	return oupu
}

// SetTargetOs sets the "target_os" edge to the OperatingSystemResource entity.
func (oupu *OSUpdatePolicyUpdate) SetTargetOs(o *OperatingSystemResource) *OSUpdatePolicyUpdate {
	return oupu.SetTargetOsID(o.ID)
}

// Mutation returns the OSUpdatePolicyMutation object of the builder.
func (oupu *OSUpdatePolicyUpdate) Mutation() *OSUpdatePolicyMutation {
	return oupu.mutation
}

// ClearTargetOs clears the "target_os" edge to the OperatingSystemResource entity.
func (oupu *OSUpdatePolicyUpdate) ClearTargetOs() *OSUpdatePolicyUpdate {
	oupu.mutation.ClearTargetOs()
	return oupu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (oupu *OSUpdatePolicyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, oupu.sqlSave, oupu.mutation, oupu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (oupu *OSUpdatePolicyUpdate) SaveX(ctx context.Context) int {
	affected, err := oupu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (oupu *OSUpdatePolicyUpdate) Exec(ctx context.Context) error {
	_, err := oupu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (oupu *OSUpdatePolicyUpdate) ExecX(ctx context.Context) {
	if err := oupu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (oupu *OSUpdatePolicyUpdate) check() error {
	if v, ok := oupu.mutation.UpdatePolicy(); ok {
		if err := osupdatepolicy.UpdatePolicyValidator(v); err != nil {
			return &ValidationError{Name: "update_policy", err: fmt.Errorf(`ent: validator failed for field "OSUpdatePolicy.update_policy": %w`, err)}
		}
	}
	return nil
}

func (oupu *OSUpdatePolicyUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := oupu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(osupdatepolicy.Table, osupdatepolicy.Columns, sqlgraph.NewFieldSpec(osupdatepolicy.FieldID, field.TypeInt))
	if ps := oupu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := oupu.mutation.ResourceID(); ok {
		_spec.SetField(osupdatepolicy.FieldResourceID, field.TypeString, value)
	}
	if value, ok := oupu.mutation.InstalledPackages(); ok {
		_spec.SetField(osupdatepolicy.FieldInstalledPackages, field.TypeString, value)
	}
	if oupu.mutation.InstalledPackagesCleared() {
		_spec.ClearField(osupdatepolicy.FieldInstalledPackages, field.TypeString)
	}
	if value, ok := oupu.mutation.UpdateSources(); ok {
		_spec.SetField(osupdatepolicy.FieldUpdateSources, field.TypeString, value)
	}
	if oupu.mutation.UpdateSourcesCleared() {
		_spec.ClearField(osupdatepolicy.FieldUpdateSources, field.TypeString)
	}
	if value, ok := oupu.mutation.KernelCommand(); ok {
		_spec.SetField(osupdatepolicy.FieldKernelCommand, field.TypeString, value)
	}
	if oupu.mutation.KernelCommandCleared() {
		_spec.ClearField(osupdatepolicy.FieldKernelCommand, field.TypeString)
	}
	if value, ok := oupu.mutation.UpdatePolicy(); ok {
		_spec.SetField(osupdatepolicy.FieldUpdatePolicy, field.TypeEnum, value)
	}
	if oupu.mutation.UpdatePolicyCleared() {
		_spec.ClearField(osupdatepolicy.FieldUpdatePolicy, field.TypeEnum)
	}
	if value, ok := oupu.mutation.UpdatedAt(); ok {
		_spec.SetField(osupdatepolicy.FieldUpdatedAt, field.TypeString, value)
	}
	if oupu.mutation.TargetOsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   osupdatepolicy.TargetOsTable,
			Columns: []string{osupdatepolicy.TargetOsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(operatingsystemresource.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := oupu.mutation.TargetOsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   osupdatepolicy.TargetOsTable,
			Columns: []string{osupdatepolicy.TargetOsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(operatingsystemresource.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, oupu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{osupdatepolicy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	oupu.mutation.done = true
	return n, nil
}

// OSUpdatePolicyUpdateOne is the builder for updating a single OSUpdatePolicy entity.
type OSUpdatePolicyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OSUpdatePolicyMutation
}

// SetResourceID sets the "resource_id" field.
func (oupuo *OSUpdatePolicyUpdateOne) SetResourceID(s string) *OSUpdatePolicyUpdateOne {
	oupuo.mutation.SetResourceID(s)
	return oupuo
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (oupuo *OSUpdatePolicyUpdateOne) SetNillableResourceID(s *string) *OSUpdatePolicyUpdateOne {
	if s != nil {
		oupuo.SetResourceID(*s)
	}
	return oupuo
}

// SetInstalledPackages sets the "installed_packages" field.
func (oupuo *OSUpdatePolicyUpdateOne) SetInstalledPackages(s string) *OSUpdatePolicyUpdateOne {
	oupuo.mutation.SetInstalledPackages(s)
	return oupuo
}

// SetNillableInstalledPackages sets the "installed_packages" field if the given value is not nil.
func (oupuo *OSUpdatePolicyUpdateOne) SetNillableInstalledPackages(s *string) *OSUpdatePolicyUpdateOne {
	if s != nil {
		oupuo.SetInstalledPackages(*s)
	}
	return oupuo
}

// ClearInstalledPackages clears the value of the "installed_packages" field.
func (oupuo *OSUpdatePolicyUpdateOne) ClearInstalledPackages() *OSUpdatePolicyUpdateOne {
	oupuo.mutation.ClearInstalledPackages()
	return oupuo
}

// SetUpdateSources sets the "update_sources" field.
func (oupuo *OSUpdatePolicyUpdateOne) SetUpdateSources(s string) *OSUpdatePolicyUpdateOne {
	oupuo.mutation.SetUpdateSources(s)
	return oupuo
}

// SetNillableUpdateSources sets the "update_sources" field if the given value is not nil.
func (oupuo *OSUpdatePolicyUpdateOne) SetNillableUpdateSources(s *string) *OSUpdatePolicyUpdateOne {
	if s != nil {
		oupuo.SetUpdateSources(*s)
	}
	return oupuo
}

// ClearUpdateSources clears the value of the "update_sources" field.
func (oupuo *OSUpdatePolicyUpdateOne) ClearUpdateSources() *OSUpdatePolicyUpdateOne {
	oupuo.mutation.ClearUpdateSources()
	return oupuo
}

// SetKernelCommand sets the "kernel_command" field.
func (oupuo *OSUpdatePolicyUpdateOne) SetKernelCommand(s string) *OSUpdatePolicyUpdateOne {
	oupuo.mutation.SetKernelCommand(s)
	return oupuo
}

// SetNillableKernelCommand sets the "kernel_command" field if the given value is not nil.
func (oupuo *OSUpdatePolicyUpdateOne) SetNillableKernelCommand(s *string) *OSUpdatePolicyUpdateOne {
	if s != nil {
		oupuo.SetKernelCommand(*s)
	}
	return oupuo
}

// ClearKernelCommand clears the value of the "kernel_command" field.
func (oupuo *OSUpdatePolicyUpdateOne) ClearKernelCommand() *OSUpdatePolicyUpdateOne {
	oupuo.mutation.ClearKernelCommand()
	return oupuo
}

// SetUpdatePolicy sets the "update_policy" field.
func (oupuo *OSUpdatePolicyUpdateOne) SetUpdatePolicy(op osupdatepolicy.UpdatePolicy) *OSUpdatePolicyUpdateOne {
	oupuo.mutation.SetUpdatePolicy(op)
	return oupuo
}

// SetNillableUpdatePolicy sets the "update_policy" field if the given value is not nil.
func (oupuo *OSUpdatePolicyUpdateOne) SetNillableUpdatePolicy(op *osupdatepolicy.UpdatePolicy) *OSUpdatePolicyUpdateOne {
	if op != nil {
		oupuo.SetUpdatePolicy(*op)
	}
	return oupuo
}

// ClearUpdatePolicy clears the value of the "update_policy" field.
func (oupuo *OSUpdatePolicyUpdateOne) ClearUpdatePolicy() *OSUpdatePolicyUpdateOne {
	oupuo.mutation.ClearUpdatePolicy()
	return oupuo
}

// SetUpdatedAt sets the "updated_at" field.
func (oupuo *OSUpdatePolicyUpdateOne) SetUpdatedAt(s string) *OSUpdatePolicyUpdateOne {
	oupuo.mutation.SetUpdatedAt(s)
	return oupuo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (oupuo *OSUpdatePolicyUpdateOne) SetNillableUpdatedAt(s *string) *OSUpdatePolicyUpdateOne {
	if s != nil {
		oupuo.SetUpdatedAt(*s)
	}
	return oupuo
}

// SetTargetOsID sets the "target_os" edge to the OperatingSystemResource entity by ID.
func (oupuo *OSUpdatePolicyUpdateOne) SetTargetOsID(id int) *OSUpdatePolicyUpdateOne {
	oupuo.mutation.SetTargetOsID(id)
	return oupuo
}

// SetNillableTargetOsID sets the "target_os" edge to the OperatingSystemResource entity by ID if the given value is not nil.
func (oupuo *OSUpdatePolicyUpdateOne) SetNillableTargetOsID(id *int) *OSUpdatePolicyUpdateOne {
	if id != nil {
		oupuo = oupuo.SetTargetOsID(*id)
	}
	return oupuo
}

// SetTargetOs sets the "target_os" edge to the OperatingSystemResource entity.
func (oupuo *OSUpdatePolicyUpdateOne) SetTargetOs(o *OperatingSystemResource) *OSUpdatePolicyUpdateOne {
	return oupuo.SetTargetOsID(o.ID)
}

// Mutation returns the OSUpdatePolicyMutation object of the builder.
func (oupuo *OSUpdatePolicyUpdateOne) Mutation() *OSUpdatePolicyMutation {
	return oupuo.mutation
}

// ClearTargetOs clears the "target_os" edge to the OperatingSystemResource entity.
func (oupuo *OSUpdatePolicyUpdateOne) ClearTargetOs() *OSUpdatePolicyUpdateOne {
	oupuo.mutation.ClearTargetOs()
	return oupuo
}

// Where appends a list predicates to the OSUpdatePolicyUpdate builder.
func (oupuo *OSUpdatePolicyUpdateOne) Where(ps ...predicate.OSUpdatePolicy) *OSUpdatePolicyUpdateOne {
	oupuo.mutation.Where(ps...)
	return oupuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (oupuo *OSUpdatePolicyUpdateOne) Select(field string, fields ...string) *OSUpdatePolicyUpdateOne {
	oupuo.fields = append([]string{field}, fields...)
	return oupuo
}

// Save executes the query and returns the updated OSUpdatePolicy entity.
func (oupuo *OSUpdatePolicyUpdateOne) Save(ctx context.Context) (*OSUpdatePolicy, error) {
	return withHooks(ctx, oupuo.sqlSave, oupuo.mutation, oupuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (oupuo *OSUpdatePolicyUpdateOne) SaveX(ctx context.Context) *OSUpdatePolicy {
	node, err := oupuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (oupuo *OSUpdatePolicyUpdateOne) Exec(ctx context.Context) error {
	_, err := oupuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (oupuo *OSUpdatePolicyUpdateOne) ExecX(ctx context.Context) {
	if err := oupuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (oupuo *OSUpdatePolicyUpdateOne) check() error {
	if v, ok := oupuo.mutation.UpdatePolicy(); ok {
		if err := osupdatepolicy.UpdatePolicyValidator(v); err != nil {
			return &ValidationError{Name: "update_policy", err: fmt.Errorf(`ent: validator failed for field "OSUpdatePolicy.update_policy": %w`, err)}
		}
	}
	return nil
}

func (oupuo *OSUpdatePolicyUpdateOne) sqlSave(ctx context.Context) (_node *OSUpdatePolicy, err error) {
	if err := oupuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(osupdatepolicy.Table, osupdatepolicy.Columns, sqlgraph.NewFieldSpec(osupdatepolicy.FieldID, field.TypeInt))
	id, ok := oupuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OSUpdatePolicy.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := oupuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, osupdatepolicy.FieldID)
		for _, f := range fields {
			if !osupdatepolicy.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != osupdatepolicy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := oupuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := oupuo.mutation.ResourceID(); ok {
		_spec.SetField(osupdatepolicy.FieldResourceID, field.TypeString, value)
	}
	if value, ok := oupuo.mutation.InstalledPackages(); ok {
		_spec.SetField(osupdatepolicy.FieldInstalledPackages, field.TypeString, value)
	}
	if oupuo.mutation.InstalledPackagesCleared() {
		_spec.ClearField(osupdatepolicy.FieldInstalledPackages, field.TypeString)
	}
	if value, ok := oupuo.mutation.UpdateSources(); ok {
		_spec.SetField(osupdatepolicy.FieldUpdateSources, field.TypeString, value)
	}
	if oupuo.mutation.UpdateSourcesCleared() {
		_spec.ClearField(osupdatepolicy.FieldUpdateSources, field.TypeString)
	}
	if value, ok := oupuo.mutation.KernelCommand(); ok {
		_spec.SetField(osupdatepolicy.FieldKernelCommand, field.TypeString, value)
	}
	if oupuo.mutation.KernelCommandCleared() {
		_spec.ClearField(osupdatepolicy.FieldKernelCommand, field.TypeString)
	}
	if value, ok := oupuo.mutation.UpdatePolicy(); ok {
		_spec.SetField(osupdatepolicy.FieldUpdatePolicy, field.TypeEnum, value)
	}
	if oupuo.mutation.UpdatePolicyCleared() {
		_spec.ClearField(osupdatepolicy.FieldUpdatePolicy, field.TypeEnum)
	}
	if value, ok := oupuo.mutation.UpdatedAt(); ok {
		_spec.SetField(osupdatepolicy.FieldUpdatedAt, field.TypeString, value)
	}
	if oupuo.mutation.TargetOsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   osupdatepolicy.TargetOsTable,
			Columns: []string{osupdatepolicy.TargetOsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(operatingsystemresource.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := oupuo.mutation.TargetOsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   osupdatepolicy.TargetOsTable,
			Columns: []string{osupdatepolicy.TargetOsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(operatingsystemresource.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &OSUpdatePolicy{config: oupuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, oupuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{osupdatepolicy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	oupuo.mutation.done = true
	return _node, nil
}
