// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/open-edge-platform/infra-core/inventory/v2/internal/ent/operatingsystemresource"
	"github.com/open-edge-platform/infra-core/inventory/v2/internal/ent/osupdatepolicyresource"
)

// OSUpdatePolicyResourceCreate is the builder for creating a OSUpdatePolicyResource entity.
type OSUpdatePolicyResourceCreate struct {
	config
	mutation *OSUpdatePolicyResourceMutation
	hooks    []Hook
}

// SetResourceID sets the "resource_id" field.
func (_c *OSUpdatePolicyResourceCreate) SetResourceID(v string) *OSUpdatePolicyResourceCreate {
	_c.mutation.SetResourceID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *OSUpdatePolicyResourceCreate) SetName(v string) *OSUpdatePolicyResourceCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *OSUpdatePolicyResourceCreate) SetDescription(v string) *OSUpdatePolicyResourceCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *OSUpdatePolicyResourceCreate) SetNillableDescription(v *string) *OSUpdatePolicyResourceCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetInstallPackages sets the "install_packages" field.
func (_c *OSUpdatePolicyResourceCreate) SetInstallPackages(v string) *OSUpdatePolicyResourceCreate {
	_c.mutation.SetInstallPackages(v)
	return _c
}

// SetNillableInstallPackages sets the "install_packages" field if the given value is not nil.
func (_c *OSUpdatePolicyResourceCreate) SetNillableInstallPackages(v *string) *OSUpdatePolicyResourceCreate {
	if v != nil {
		_c.SetInstallPackages(*v)
	}
	return _c
}

// SetUpdateSources sets the "update_sources" field.
func (_c *OSUpdatePolicyResourceCreate) SetUpdateSources(v string) *OSUpdatePolicyResourceCreate {
	_c.mutation.SetUpdateSources(v)
	return _c
}

// SetNillableUpdateSources sets the "update_sources" field if the given value is not nil.
func (_c *OSUpdatePolicyResourceCreate) SetNillableUpdateSources(v *string) *OSUpdatePolicyResourceCreate {
	if v != nil {
		_c.SetUpdateSources(*v)
	}
	return _c
}

// SetKernelCommand sets the "kernel_command" field.
func (_c *OSUpdatePolicyResourceCreate) SetKernelCommand(v string) *OSUpdatePolicyResourceCreate {
	_c.mutation.SetKernelCommand(v)
	return _c
}

// SetNillableKernelCommand sets the "kernel_command" field if the given value is not nil.
func (_c *OSUpdatePolicyResourceCreate) SetNillableKernelCommand(v *string) *OSUpdatePolicyResourceCreate {
	if v != nil {
		_c.SetKernelCommand(*v)
	}
	return _c
}

// SetUpdatePackages sets the "update_packages" field.
func (_c *OSUpdatePolicyResourceCreate) SetUpdatePackages(v string) *OSUpdatePolicyResourceCreate {
	_c.mutation.SetUpdatePackages(v)
	return _c
}

// SetNillableUpdatePackages sets the "update_packages" field if the given value is not nil.
func (_c *OSUpdatePolicyResourceCreate) SetNillableUpdatePackages(v *string) *OSUpdatePolicyResourceCreate {
	if v != nil {
		_c.SetUpdatePackages(*v)
	}
	return _c
}

// SetUpdateKernelCommand sets the "update_kernel_command" field.
func (_c *OSUpdatePolicyResourceCreate) SetUpdateKernelCommand(v string) *OSUpdatePolicyResourceCreate {
	_c.mutation.SetUpdateKernelCommand(v)
	return _c
}

// SetNillableUpdateKernelCommand sets the "update_kernel_command" field if the given value is not nil.
func (_c *OSUpdatePolicyResourceCreate) SetNillableUpdateKernelCommand(v *string) *OSUpdatePolicyResourceCreate {
	if v != nil {
		_c.SetUpdateKernelCommand(*v)
	}
	return _c
}

// SetUpdatePolicy sets the "update_policy" field.
func (_c *OSUpdatePolicyResourceCreate) SetUpdatePolicy(v osupdatepolicyresource.UpdatePolicy) *OSUpdatePolicyResourceCreate {
	_c.mutation.SetUpdatePolicy(v)
	return _c
}

// SetNillableUpdatePolicy sets the "update_policy" field if the given value is not nil.
func (_c *OSUpdatePolicyResourceCreate) SetNillableUpdatePolicy(v *osupdatepolicyresource.UpdatePolicy) *OSUpdatePolicyResourceCreate {
	if v != nil {
		_c.SetUpdatePolicy(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *OSUpdatePolicyResourceCreate) SetTenantID(v string) *OSUpdatePolicyResourceCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *OSUpdatePolicyResourceCreate) SetCreatedAt(v string) *OSUpdatePolicyResourceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OSUpdatePolicyResourceCreate) SetUpdatedAt(v string) *OSUpdatePolicyResourceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetTargetOsID sets the "target_os" edge to the OperatingSystemResource entity by ID.
func (_c *OSUpdatePolicyResourceCreate) SetTargetOsID(id int) *OSUpdatePolicyResourceCreate {
	_c.mutation.SetTargetOsID(id)
	return _c
}

// SetNillableTargetOsID sets the "target_os" edge to the OperatingSystemResource entity by ID if the given value is not nil.
func (_c *OSUpdatePolicyResourceCreate) SetNillableTargetOsID(id *int) *OSUpdatePolicyResourceCreate {
	if id != nil {
		_c = _c.SetTargetOsID(*id)
	}
	return _c
}

// SetTargetOs sets the "target_os" edge to the OperatingSystemResource entity.
func (_c *OSUpdatePolicyResourceCreate) SetTargetOs(v *OperatingSystemResource) *OSUpdatePolicyResourceCreate {
	return _c.SetTargetOsID(v.ID)
}

// Mutation returns the OSUpdatePolicyResourceMutation object of the builder.
func (_c *OSUpdatePolicyResourceCreate) Mutation() *OSUpdatePolicyResourceMutation {
	return _c.mutation
}

// Save creates the OSUpdatePolicyResource in the database.
func (_c *OSUpdatePolicyResourceCreate) Save(ctx context.Context) (*OSUpdatePolicyResource, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OSUpdatePolicyResourceCreate) SaveX(ctx context.Context) *OSUpdatePolicyResource {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OSUpdatePolicyResourceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OSUpdatePolicyResourceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OSUpdatePolicyResourceCreate) check() error {
	if _, ok := _c.mutation.ResourceID(); !ok {
		return &ValidationError{Name: "resource_id", err: errors.New(`ent: missing required field "OSUpdatePolicyResource.resource_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "OSUpdatePolicyResource.name"`)}
	}
	if v, ok := _c.mutation.UpdatePolicy(); ok {
		if err := osupdatepolicyresource.UpdatePolicyValidator(v); err != nil {
			return &ValidationError{Name: "update_policy", err: fmt.Errorf(`ent: validator failed for field "OSUpdatePolicyResource.update_policy": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "OSUpdatePolicyResource.tenant_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OSUpdatePolicyResource.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OSUpdatePolicyResource.updated_at"`)}
	}
	return nil
}

func (_c *OSUpdatePolicyResourceCreate) sqlSave(ctx context.Context) (*OSUpdatePolicyResource, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OSUpdatePolicyResourceCreate) createSpec() (*OSUpdatePolicyResource, *sqlgraph.CreateSpec) {
	var (
		_node = &OSUpdatePolicyResource{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(osupdatepolicyresource.Table, sqlgraph.NewFieldSpec(osupdatepolicyresource.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.ResourceID(); ok {
		_spec.SetField(osupdatepolicyresource.FieldResourceID, field.TypeString, value)
		_node.ResourceID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(osupdatepolicyresource.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(osupdatepolicyresource.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.InstallPackages(); ok {
		_spec.SetField(osupdatepolicyresource.FieldInstallPackages, field.TypeString, value)
		_node.InstallPackages = value
	}
	if value, ok := _c.mutation.UpdateSources(); ok {
		_spec.SetField(osupdatepolicyresource.FieldUpdateSources, field.TypeString, value)
		_node.UpdateSources = value
	}
	if value, ok := _c.mutation.KernelCommand(); ok {
		_spec.SetField(osupdatepolicyresource.FieldKernelCommand, field.TypeString, value)
		_node.KernelCommand = value
	}
	if value, ok := _c.mutation.UpdatePackages(); ok {
		_spec.SetField(osupdatepolicyresource.FieldUpdatePackages, field.TypeString, value)
		_node.UpdatePackages = value
	}
	if value, ok := _c.mutation.UpdateKernelCommand(); ok {
		_spec.SetField(osupdatepolicyresource.FieldUpdateKernelCommand, field.TypeString, value)
		_node.UpdateKernelCommand = value
	}
	if value, ok := _c.mutation.UpdatePolicy(); ok {
		_spec.SetField(osupdatepolicyresource.FieldUpdatePolicy, field.TypeEnum, value)
		_node.UpdatePolicy = value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(osupdatepolicyresource.FieldTenantID, field.TypeString, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(osupdatepolicyresource.FieldCreatedAt, field.TypeString, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(osupdatepolicyresource.FieldUpdatedAt, field.TypeString, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.TargetOsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   osupdatepolicyresource.TargetOsTable,
			Columns: []string{osupdatepolicyresource.TargetOsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(operatingsystemresource.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.os_update_policy_resource_target_os = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OSUpdatePolicyResourceCreateBulk is the builder for creating many OSUpdatePolicyResource entities in bulk.
type OSUpdatePolicyResourceCreateBulk struct {
	config
	err      error
	builders []*OSUpdatePolicyResourceCreate
}

// Save creates the OSUpdatePolicyResource entities in the database.
func (_c *OSUpdatePolicyResourceCreateBulk) Save(ctx context.Context) ([]*OSUpdatePolicyResource, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OSUpdatePolicyResource, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OSUpdatePolicyResourceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OSUpdatePolicyResourceCreateBulk) SaveX(ctx context.Context) []*OSUpdatePolicyResource {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OSUpdatePolicyResourceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OSUpdatePolicyResourceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
