// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/open-edge-platform/infra-core/inventory/v2/internal/ent/regionresource"
)

// RegionResourceCreate is the builder for creating a RegionResource entity.
type RegionResourceCreate struct {
	config
	mutation *RegionResourceMutation
	hooks    []Hook
}

// SetResourceID sets the "resource_id" field.
func (_c *RegionResourceCreate) SetResourceID(v string) *RegionResourceCreate {
	_c.mutation.SetResourceID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *RegionResourceCreate) SetName(v string) *RegionResourceCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *RegionResourceCreate) SetNillableName(v *string) *RegionResourceCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetRegionKind sets the "region_kind" field.
func (_c *RegionResourceCreate) SetRegionKind(v string) *RegionResourceCreate {
	_c.mutation.SetRegionKind(v)
	return _c
}

// SetNillableRegionKind sets the "region_kind" field if the given value is not nil.
func (_c *RegionResourceCreate) SetNillableRegionKind(v *string) *RegionResourceCreate {
	if v != nil {
		_c.SetRegionKind(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *RegionResourceCreate) SetMetadata(v string) *RegionResourceCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetNillableMetadata sets the "metadata" field if the given value is not nil.
func (_c *RegionResourceCreate) SetNillableMetadata(v *string) *RegionResourceCreate {
	if v != nil {
		_c.SetMetadata(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *RegionResourceCreate) SetTenantID(v string) *RegionResourceCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RegionResourceCreate) SetCreatedAt(v string) *RegionResourceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RegionResourceCreate) SetUpdatedAt(v string) *RegionResourceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetParentRegionID sets the "parent_region" edge to the RegionResource entity by ID.
func (_c *RegionResourceCreate) SetParentRegionID(id int) *RegionResourceCreate {
	_c.mutation.SetParentRegionID(id)
	return _c
}

// SetNillableParentRegionID sets the "parent_region" edge to the RegionResource entity by ID if the given value is not nil.
func (_c *RegionResourceCreate) SetNillableParentRegionID(id *int) *RegionResourceCreate {
	if id != nil {
		_c = _c.SetParentRegionID(*id)
	}
	return _c
}

// SetParentRegion sets the "parent_region" edge to the RegionResource entity.
func (_c *RegionResourceCreate) SetParentRegion(v *RegionResource) *RegionResourceCreate {
	return _c.SetParentRegionID(v.ID)
}

// AddChildIDs adds the "children" edge to the RegionResource entity by IDs.
func (_c *RegionResourceCreate) AddChildIDs(ids ...int) *RegionResourceCreate {
	_c.mutation.AddChildIDs(ids...)
	return _c
}

// AddChildren adds the "children" edges to the RegionResource entity.
func (_c *RegionResourceCreate) AddChildren(v ...*RegionResource) *RegionResourceCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChildIDs(ids...)
}

// Mutation returns the RegionResourceMutation object of the builder.
func (_c *RegionResourceCreate) Mutation() *RegionResourceMutation {
	return _c.mutation
}

// Save creates the RegionResource in the database.
func (_c *RegionResourceCreate) Save(ctx context.Context) (*RegionResource, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RegionResourceCreate) SaveX(ctx context.Context) *RegionResource {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RegionResourceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RegionResourceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RegionResourceCreate) check() error {
	if _, ok := _c.mutation.ResourceID(); !ok {
		return &ValidationError{Name: "resource_id", err: errors.New(`ent: missing required field "RegionResource.resource_id"`)}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "RegionResource.tenant_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RegionResource.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RegionResource.updated_at"`)}
	}
	return nil
}

func (_c *RegionResourceCreate) sqlSave(ctx context.Context) (*RegionResource, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RegionResourceCreate) createSpec() (*RegionResource, *sqlgraph.CreateSpec) {
	var (
		_node = &RegionResource{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(regionresource.Table, sqlgraph.NewFieldSpec(regionresource.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.ResourceID(); ok {
		_spec.SetField(regionresource.FieldResourceID, field.TypeString, value)
		_node.ResourceID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(regionresource.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.RegionKind(); ok {
		_spec.SetField(regionresource.FieldRegionKind, field.TypeString, value)
		_node.RegionKind = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(regionresource.FieldMetadata, field.TypeString, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(regionresource.FieldTenantID, field.TypeString, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(regionresource.FieldCreatedAt, field.TypeString, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(regionresource.FieldUpdatedAt, field.TypeString, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ParentRegionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   regionresource.ParentRegionTable,
			Columns: []string{regionresource.ParentRegionColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(regionresource.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.region_resource_parent_region = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   regionresource.ChildrenTable,
			Columns: []string{regionresource.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(regionresource.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RegionResourceCreateBulk is the builder for creating many RegionResource entities in bulk.
type RegionResourceCreateBulk struct {
	config
	err      error
	builders []*RegionResourceCreate
}

// Save creates the RegionResource entities in the database.
func (_c *RegionResourceCreateBulk) Save(ctx context.Context) ([]*RegionResource, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RegionResource, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RegionResourceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RegionResourceCreateBulk) SaveX(ctx context.Context) []*RegionResource {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RegionResourceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RegionResourceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
