// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/open-edge-platform/infra-core/inventory/v2/internal/ent/ouresource"
	"github.com/open-edge-platform/infra-core/inventory/v2/internal/ent/predicate"
	"github.com/open-edge-platform/infra-core/inventory/v2/internal/ent/providerresource"
	"github.com/open-edge-platform/infra-core/inventory/v2/internal/ent/regionresource"
	"github.com/open-edge-platform/infra-core/inventory/v2/internal/ent/siteresource"
)

// SiteResourceQuery is the builder for querying SiteResource entities.
type SiteResourceQuery struct {
	config
	ctx          *QueryContext
	order        []siteresource.OrderOption
	inters       []Interceptor
	predicates   []predicate.SiteResource
	withRegion   *RegionResourceQuery
	withOu       *OuResourceQuery
	withProvider *ProviderResourceQuery
	withFKs      bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SiteResourceQuery builder.
func (_q *SiteResourceQuery) Where(ps ...predicate.SiteResource) *SiteResourceQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *SiteResourceQuery) Limit(limit int) *SiteResourceQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *SiteResourceQuery) Offset(offset int) *SiteResourceQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *SiteResourceQuery) Unique(unique bool) *SiteResourceQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *SiteResourceQuery) Order(o ...siteresource.OrderOption) *SiteResourceQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryRegion chains the current query on the "region" edge.
func (_q *SiteResourceQuery) QueryRegion() *RegionResourceQuery {
	query := (&RegionResourceClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(siteresource.Table, siteresource.FieldID, selector),
			sqlgraph.To(regionresource.Table, regionresource.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, siteresource.RegionTable, siteresource.RegionColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryOu chains the current query on the "ou" edge.
func (_q *SiteResourceQuery) QueryOu() *OuResourceQuery {
	query := (&OuResourceClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(siteresource.Table, siteresource.FieldID, selector),
			sqlgraph.To(ouresource.Table, ouresource.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, siteresource.OuTable, siteresource.OuColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryProvider chains the current query on the "provider" edge.
func (_q *SiteResourceQuery) QueryProvider() *ProviderResourceQuery {
	query := (&ProviderResourceClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(siteresource.Table, siteresource.FieldID, selector),
			sqlgraph.To(providerresource.Table, providerresource.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, siteresource.ProviderTable, siteresource.ProviderColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SiteResource entity from the query.
// Returns a *NotFoundError when no SiteResource was found.
func (_q *SiteResourceQuery) First(ctx context.Context) (*SiteResource, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{siteresource.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *SiteResourceQuery) FirstX(ctx context.Context) *SiteResource {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SiteResource ID from the query.
// Returns a *NotFoundError when no SiteResource ID was found.
func (_q *SiteResourceQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{siteresource.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *SiteResourceQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SiteResource entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SiteResource entity is found.
// Returns a *NotFoundError when no SiteResource entities are found.
func (_q *SiteResourceQuery) Only(ctx context.Context) (*SiteResource, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{siteresource.Label}
	default:
		return nil, &NotSingularError{siteresource.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *SiteResourceQuery) OnlyX(ctx context.Context) *SiteResource {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SiteResource ID in the query.
// Returns a *NotSingularError when more than one SiteResource ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *SiteResourceQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{siteresource.Label}
	default:
		err = &NotSingularError{siteresource.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *SiteResourceQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SiteResources.
func (_q *SiteResourceQuery) All(ctx context.Context) ([]*SiteResource, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SiteResource, *SiteResourceQuery]()
	return withInterceptors[[]*SiteResource](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *SiteResourceQuery) AllX(ctx context.Context) []*SiteResource {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SiteResource IDs.
func (_q *SiteResourceQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(siteresource.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *SiteResourceQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *SiteResourceQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*SiteResourceQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *SiteResourceQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *SiteResourceQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *SiteResourceQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SiteResourceQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *SiteResourceQuery) Clone() *SiteResourceQuery {
	if _q == nil {
		return nil
	}
	return &SiteResourceQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]siteresource.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.SiteResource{}, _q.predicates...),
		withRegion:   _q.withRegion.Clone(),
		withOu:       _q.withOu.Clone(),
		withProvider: _q.withProvider.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithRegion tells the query-builder to eager-load the nodes that are connected to
// the "region" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SiteResourceQuery) WithRegion(opts ...func(*RegionResourceQuery)) *SiteResourceQuery {
	query := (&RegionResourceClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRegion = query
	return _q
}

// WithOu tells the query-builder to eager-load the nodes that are connected to
// the "ou" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SiteResourceQuery) WithOu(opts ...func(*OuResourceQuery)) *SiteResourceQuery {
	query := (&OuResourceClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withOu = query
	return _q
}

// WithProvider tells the query-builder to eager-load the nodes that are connected to
// the "provider" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SiteResourceQuery) WithProvider(opts ...func(*ProviderResourceQuery)) *SiteResourceQuery {
	query := (&ProviderResourceClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProvider = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ResourceID string `json:"resource_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SiteResource.Query().
//		GroupBy(siteresource.FieldResourceID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *SiteResourceQuery) GroupBy(field string, fields ...string) *SiteResourceGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SiteResourceGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = siteresource.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ResourceID string `json:"resource_id,omitempty"`
//	}
//
//	client.SiteResource.Query().
//		Select(siteresource.FieldResourceID).
//		Scan(ctx, &v)
func (_q *SiteResourceQuery) Select(fields ...string) *SiteResourceSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &SiteResourceSelect{SiteResourceQuery: _q}
	sbuild.label = siteresource.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SiteResourceSelect configured with the given aggregations.
func (_q *SiteResourceQuery) Aggregate(fns ...AggregateFunc) *SiteResourceSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *SiteResourceQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !siteresource.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *SiteResourceQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SiteResource, error) {
	var (
		nodes       = []*SiteResource{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withRegion != nil,
			_q.withOu != nil,
			_q.withProvider != nil,
		}
	)
	if _q.withRegion != nil || _q.withOu != nil || _q.withProvider != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, siteresource.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SiteResource).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SiteResource{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withRegion; query != nil {
		if err := _q.loadRegion(ctx, query, nodes, nil,
			func(n *SiteResource, e *RegionResource) { n.Edges.Region = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withOu; query != nil {
		if err := _q.loadOu(ctx, query, nodes, nil,
			func(n *SiteResource, e *OuResource) { n.Edges.Ou = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withProvider; query != nil {
		if err := _q.loadProvider(ctx, query, nodes, nil,
			func(n *SiteResource, e *ProviderResource) { n.Edges.Provider = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *SiteResourceQuery) loadRegion(ctx context.Context, query *RegionResourceQuery, nodes []*SiteResource, init func(*SiteResource), assign func(*SiteResource, *RegionResource)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*SiteResource)
	for i := range nodes {
		if nodes[i].site_resource_region == nil {
			continue
		}
		fk := *nodes[i].site_resource_region
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(regionresource.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "site_resource_region" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *SiteResourceQuery) loadOu(ctx context.Context, query *OuResourceQuery, nodes []*SiteResource, init func(*SiteResource), assign func(*SiteResource, *OuResource)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*SiteResource)
	for i := range nodes {
		if nodes[i].site_resource_ou == nil {
			continue
		}
		fk := *nodes[i].site_resource_ou
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(ouresource.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "site_resource_ou" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *SiteResourceQuery) loadProvider(ctx context.Context, query *ProviderResourceQuery, nodes []*SiteResource, init func(*SiteResource), assign func(*SiteResource, *ProviderResource)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*SiteResource)
	for i := range nodes {
		if nodes[i].site_resource_provider == nil {
			continue
		}
		fk := *nodes[i].site_resource_provider
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(providerresource.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "site_resource_provider" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *SiteResourceQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *SiteResourceQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(siteresource.Table, siteresource.Columns, sqlgraph.NewFieldSpec(siteresource.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, siteresource.FieldID)
		for i := range fields {
			if fields[i] != siteresource.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *SiteResourceQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(siteresource.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = siteresource.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SiteResourceGroupBy is the group-by builder for SiteResource entities.
type SiteResourceGroupBy struct {
	selector
	build *SiteResourceQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *SiteResourceGroupBy) Aggregate(fns ...AggregateFunc) *SiteResourceGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *SiteResourceGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SiteResourceQuery, *SiteResourceGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *SiteResourceGroupBy) sqlScan(ctx context.Context, root *SiteResourceQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SiteResourceSelect is the builder for selecting fields of SiteResource entities.
type SiteResourceSelect struct {
	*SiteResourceQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *SiteResourceSelect) Aggregate(fns ...AggregateFunc) *SiteResourceSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *SiteResourceSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SiteResourceQuery, *SiteResourceSelect](ctx, _s.SiteResourceQuery, _s, _s.inters, v)
}

func (_s *SiteResourceSelect) sqlScan(ctx context.Context, root *SiteResourceQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
