// SPDX-FileCopyrightText: (C) 2025 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: resources/os/v1/os.proto

package osv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/open-edge-platform/infra-core/apiv2/v2/internal/pbapi/resources/common/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SecurityFeature describes the security capabilities of a resource.
type SecurityFeature int32

const (
	SecurityFeature_SECURITY_FEATURE_UNSPECIFIED                          SecurityFeature = 0
	SecurityFeature_SECURITY_FEATURE_NONE                                 SecurityFeature = 1
	SecurityFeature_SECURITY_FEATURE_SECURE_BOOT_AND_FULL_DISK_ENCRYPTION SecurityFeature = 2
)

// Enum value maps for SecurityFeature.
var (
	SecurityFeature_name = map[int32]string{
		0: "SECURITY_FEATURE_UNSPECIFIED",
		1: "SECURITY_FEATURE_NONE",
		2: "SECURITY_FEATURE_SECURE_BOOT_AND_FULL_DISK_ENCRYPTION",
	}
	SecurityFeature_value = map[string]int32{
		"SECURITY_FEATURE_UNSPECIFIED":                          0,
		"SECURITY_FEATURE_NONE":                                 1,
		"SECURITY_FEATURE_SECURE_BOOT_AND_FULL_DISK_ENCRYPTION": 2,
	}
)

func (x SecurityFeature) Enum() *SecurityFeature {
	p := new(SecurityFeature)
	*p = x
	return p
}

func (x SecurityFeature) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecurityFeature) Descriptor() protoreflect.EnumDescriptor {
	return file_resources_os_v1_os_proto_enumTypes[0].Descriptor()
}

func (SecurityFeature) Type() protoreflect.EnumType {
	return &file_resources_os_v1_os_proto_enumTypes[0]
}

func (x SecurityFeature) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SecurityFeature.Descriptor instead.
func (SecurityFeature) EnumDescriptor() ([]byte, []int) {
	return file_resources_os_v1_os_proto_rawDescGZIP(), []int{0}
}

// OsType describes type of operating system.
type OsType int32

const (
	OsType_OS_TYPE_UNSPECIFIED OsType = 0
	OsType_OS_TYPE_MUTABLE     OsType = 1
	OsType_OS_TYPE_IMMUTABLE   OsType = 2
)

// Enum value maps for OsType.
var (
	OsType_name = map[int32]string{
		0: "OS_TYPE_UNSPECIFIED",
		1: "OS_TYPE_MUTABLE",
		2: "OS_TYPE_IMMUTABLE",
	}
	OsType_value = map[string]int32{
		"OS_TYPE_UNSPECIFIED": 0,
		"OS_TYPE_MUTABLE":     1,
		"OS_TYPE_IMMUTABLE":   2,
	}
)

func (x OsType) Enum() *OsType {
	p := new(OsType)
	*p = x
	return p
}

func (x OsType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OsType) Descriptor() protoreflect.EnumDescriptor {
	return file_resources_os_v1_os_proto_enumTypes[1].Descriptor()
}

func (OsType) Type() protoreflect.EnumType {
	return &file_resources_os_v1_os_proto_enumTypes[1]
}

func (x OsType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OsType.Descriptor instead.
func (OsType) EnumDescriptor() ([]byte, []int) {
	return file_resources_os_v1_os_proto_rawDescGZIP(), []int{1}
}

// OsProviderKind describes "owner" of the OS, that will drive OS provisioning.
type OsProviderKind int32

const (
	OsProviderKind_OS_PROVIDER_KIND_UNSPECIFIED OsProviderKind = 0
	OsProviderKind_OS_PROVIDER_KIND_INFRA       OsProviderKind = 1
	OsProviderKind_OS_PROVIDER_KIND_LENOVO      OsProviderKind = 2
)

// Enum value maps for OsProviderKind.
var (
	OsProviderKind_name = map[int32]string{
		0: "OS_PROVIDER_KIND_UNSPECIFIED",
		1: "OS_PROVIDER_KIND_INFRA",
		2: "OS_PROVIDER_KIND_LENOVO",
	}
	OsProviderKind_value = map[string]int32{
		"OS_PROVIDER_KIND_UNSPECIFIED": 0,
		"OS_PROVIDER_KIND_INFRA":       1,
		"OS_PROVIDER_KIND_LENOVO":      2,
	}
)

func (x OsProviderKind) Enum() *OsProviderKind {
	p := new(OsProviderKind)
	*p = x
	return p
}

func (x OsProviderKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OsProviderKind) Descriptor() protoreflect.EnumDescriptor {
	return file_resources_os_v1_os_proto_enumTypes[2].Descriptor()
}

func (OsProviderKind) Type() protoreflect.EnumType {
	return &file_resources_os_v1_os_proto_enumTypes[2]
}

func (x OsProviderKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OsProviderKind.Descriptor instead.
func (OsProviderKind) EnumDescriptor() ([]byte, []int) {
	return file_resources_os_v1_os_proto_rawDescGZIP(), []int{2}
}

// An OS resource.
type OperatingSystemResource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource ID, generated by inventory on Create.
	ResourceId string `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	// The OS resource's name.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The OS resource's CPU architecture.
	Architecture string `protobuf:"bytes,3,opt,name=architecture,proto3" json:"architecture,omitempty"`
	// The URL repository of the OS image.
	ImageUrl string `protobuf:"bytes,6,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	// A unique identifier of the OS image that can be retrieved from the running OS.
	ImageId     string `protobuf:"bytes,13,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	Description string `protobuf:"bytes,16,opt,name=description,proto3" json:"description,omitempty"`
	// SHA256 checksum of the OS resource in hexadecimal representation.
	Sha256 string `protobuf:"bytes,7,opt,name=sha256,proto3" json:"sha256,omitempty"`
	// Name of an OS profile that the OS resource belongs to. Uniquely identifies a family of OS resources.
	ProfileName string `protobuf:"bytes,8,opt,name=profile_name,json=profileName,proto3" json:"profile_name,omitempty"`
	// Version of OS profile that the OS resource belongs to.
	ProfileVersion string `protobuf:"bytes,12,opt,name=profile_version,json=profileVersion,proto3" json:"profile_version,omitempty"`
	// List of installed packages, encoded as a JSON list.
	InstalledPackages string `protobuf:"bytes,9,opt,name=installed_packages,json=installedPackages,proto3" json:"installed_packages,omitempty"`
	// The URL of the OS manifest which contains install packages details. This will be used to fill the installed_packages field
	// for the advance use case to allow manual creation of OSProfiles when supported from backend.
	InstalledPackagesUrl string `protobuf:"bytes,17,opt,name=installed_packages_url,json=installedPackagesUrl,proto3" json:"installed_packages_url,omitempty"`
	// Indicating if this OS is capable of supporting features like Secure Boot (SB) and Full Disk Encryption (FDE).
	// Immutable after creation.
	SecurityFeature SecurityFeature `protobuf:"varint,10,opt,name=security_feature,json=securityFeature,proto3,enum=resources.os.v1.SecurityFeature" json:"security_feature,omitempty"`
	// Indicating the type of OS (for example, mutable or immutable).
	OsType OsType `protobuf:"varint,11,opt,name=os_type,json=osType,proto3,enum=resources.os.v1.OsType" json:"os_type,omitempty"`
	// Indicating the provider of OS (e.g., Infra or Lenovo).
	OsProvider OsProviderKind `protobuf:"varint,14,opt,name=os_provider,json=osProvider,proto3,enum=resources.os.v1.OsProviderKind" json:"os_provider,omitempty"`
	// Opaque JSON field storing references to custom installation script(s) that
	// supplements the base OS with additional OS-level dependencies/configurations.
	// If empty, the default OS installation will be used.
	PlatformBundle string `protobuf:"bytes,15,opt,name=platform_bundle,json=platformBundle,proto3" json:"platform_bundle,omitempty"`
	// Opaque JSON field storing metadata associated to this OS resource. Expected to be a JSON object with string keys and values, or an empty string.
	Metadata string `protobuf:"bytes,18,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// user-provided, TLS CA Certificate
	TlsCaCert string `protobuf:"bytes,19,opt,name=tls_ca_cert,json=tlsCaCert,proto3" json:"tls_ca_cert,omitempty"`
	// URL of the file containing information about the existing CVEs on the Operating System.
	ExistingCvesUrl string `protobuf:"bytes,42,opt,name=existing_cves_url,json=existingCvesUrl,proto3" json:"existing_cves_url,omitempty"`
	// The CVEs that are currently present on the Operating System, encoded as a JSON list.
	ExistingCves string `protobuf:"bytes,43,opt,name=existing_cves,json=existingCves,proto3" json:"existing_cves,omitempty"`
	// URL of the file containing information about the CVEs that have been fixed by this OS Resource version.
	FixedCvesUrl string `protobuf:"bytes,44,opt,name=fixed_cves_url,json=fixedCvesUrl,proto3" json:"fixed_cves_url,omitempty"`
	// The CVEs that have been fixed by this OS Resource version, encoded as a JSON list.
	FixedCves string `protobuf:"bytes,45,opt,name=fixed_cves,json=fixedCves,proto3" json:"fixed_cves,omitempty"`
	// Deprecated, The OS resource's unique identifier. Alias of resourceId.
	OsResourceID string `protobuf:"bytes,5001,opt,name=os_resourceID,json=osResourceID,proto3" json:"os_resourceID,omitempty"`
	// Deprecated. OS image URL. URL of the original installation source.
	RepoUrl string `protobuf:"bytes,5002,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	// Timestamps associated to the resource.
	Timestamps    *v1.Timestamps `protobuf:"bytes,50100,opt,name=timestamps,proto3" json:"timestamps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperatingSystemResource) Reset() {
	*x = OperatingSystemResource{}
	mi := &file_resources_os_v1_os_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatingSystemResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatingSystemResource) ProtoMessage() {}

func (x *OperatingSystemResource) ProtoReflect() protoreflect.Message {
	mi := &file_resources_os_v1_os_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatingSystemResource.ProtoReflect.Descriptor instead.
func (*OperatingSystemResource) Descriptor() ([]byte, []int) {
	return file_resources_os_v1_os_proto_rawDescGZIP(), []int{0}
}

func (x *OperatingSystemResource) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *OperatingSystemResource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OperatingSystemResource) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *OperatingSystemResource) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *OperatingSystemResource) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *OperatingSystemResource) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *OperatingSystemResource) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *OperatingSystemResource) GetProfileName() string {
	if x != nil {
		return x.ProfileName
	}
	return ""
}

func (x *OperatingSystemResource) GetProfileVersion() string {
	if x != nil {
		return x.ProfileVersion
	}
	return ""
}

func (x *OperatingSystemResource) GetInstalledPackages() string {
	if x != nil {
		return x.InstalledPackages
	}
	return ""
}

func (x *OperatingSystemResource) GetInstalledPackagesUrl() string {
	if x != nil {
		return x.InstalledPackagesUrl
	}
	return ""
}

func (x *OperatingSystemResource) GetSecurityFeature() SecurityFeature {
	if x != nil {
		return x.SecurityFeature
	}
	return SecurityFeature_SECURITY_FEATURE_UNSPECIFIED
}

func (x *OperatingSystemResource) GetOsType() OsType {
	if x != nil {
		return x.OsType
	}
	return OsType_OS_TYPE_UNSPECIFIED
}

func (x *OperatingSystemResource) GetOsProvider() OsProviderKind {
	if x != nil {
		return x.OsProvider
	}
	return OsProviderKind_OS_PROVIDER_KIND_UNSPECIFIED
}

func (x *OperatingSystemResource) GetPlatformBundle() string {
	if x != nil {
		return x.PlatformBundle
	}
	return ""
}

func (x *OperatingSystemResource) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *OperatingSystemResource) GetTlsCaCert() string {
	if x != nil {
		return x.TlsCaCert
	}
	return ""
}

func (x *OperatingSystemResource) GetExistingCvesUrl() string {
	if x != nil {
		return x.ExistingCvesUrl
	}
	return ""
}

func (x *OperatingSystemResource) GetExistingCves() string {
	if x != nil {
		return x.ExistingCves
	}
	return ""
}

func (x *OperatingSystemResource) GetFixedCvesUrl() string {
	if x != nil {
		return x.FixedCvesUrl
	}
	return ""
}

func (x *OperatingSystemResource) GetFixedCves() string {
	if x != nil {
		return x.FixedCves
	}
	return ""
}

func (x *OperatingSystemResource) GetOsResourceID() string {
	if x != nil {
		return x.OsResourceID
	}
	return ""
}

func (x *OperatingSystemResource) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

func (x *OperatingSystemResource) GetTimestamps() *v1.Timestamps {
	if x != nil {
		return x.Timestamps
	}
	return nil
}

var File_resources_os_v1_os_proto protoreflect.FileDescriptor

const file_resources_os_v1_os_proto_rawDesc = "" +
	"\n" +
	"\x18resources/os/v1/os.proto\x12\x0fresources.os.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a resources/common/v1/common.proto\x1a\x1bbuf/validate/validate.proto\"\x82\x0e\n" +
	"\x17OperatingSystemResource\x12=\n" +
	"\vresource_id\x18\x01 \x01(\tB\x1c\xe0A\x03\xbaH\x16r\x14\x18\v2\x10^os-[0-9a-f]{8}$R\n" +
	"resourceId\x127\n" +
	"\x04name\x18\x02 \x01(\tB#\xbaH r\x1e\x18\x80\x012\x19^$|^[a-zA-Z-_0-9./: ()]+$R\x04name\x12Q\n" +
	"\farchitecture\x18\x03 \x01(\tB-\xbaH*r(\x18\x142$^$|^[a-zA-Z-_0-9./:;=@?!#,<>*()\" ]+$R\farchitecture\x12L\n" +
	"\timage_url\x18\x06 \x01(\tB/\xbaH,r*\x18\xf4\x032%^$|^[a-zA-Z-_0-9./:;=@?!#,<>*()\"\\ ]+$R\bimageUrl\x12J\n" +
	"\bimage_id\x18\r \x01(\tB/\xbaH,r*\x18\xf4\x032%^$|^[a-zA-Z-_0-9./:;=@?!#,<>*()\"\\ ]+$R\aimageId\x12Y\n" +
	"\vdescription\x18\x10 \x01(\tB7\xbaH4r2\x18\xe8\a2-^$|^[a-zA-Z-_0-9.:;=@?!#,<>*(){}&%$`^\\+\\- ]+$R\vdescription\x121\n" +
	"\x06sha256\x18\a \x01(\tB\x19\xe0A\x02\xbaH\x13r\x11\x10@\x18@2\v^[a-f0-9]+$R\x06sha256\x12R\n" +
	"\fprofile_name\x18\b \x01(\tB/\xbaH,r*\x18\x80\x012%^$|^[a-zA-Z-_0-9./:;=@?!#,<>*()\"\\ ]+$R\vprofileName\x12,\n" +
	"\x0fprofile_version\x18\f \x01(\tB\x03\xe0A\x03R\x0eprofileVersion\x12e\n" +
	"\x12installed_packages\x18\t \x01(\tB6\xe0A\x03\xbaH0r.\x18\xa0\xc2\x1e2(^$|^[a-zA-Z-_0-9./:;=@?!#,<>*()\" \\\\\\n]+$R\x11installedPackages\x12D\n" +
	"\x16installed_packages_url\x18\x11 \x01(\tB\x0e\xe0A\x05\xbaH\br\x06\x18\xc8\x01\x90\x01\x01R\x14installedPackagesUrl\x12K\n" +
	"\x10security_feature\x18\n" +
	" \x01(\x0e2 .resources.os.v1.SecurityFeatureR\x0fsecurityFeature\x120\n" +
	"\aos_type\x18\v \x01(\x0e2\x17.resources.os.v1.OsTypeR\x06osType\x12@\n" +
	"\vos_provider\x18\x0e \x01(\x0e2\x1f.resources.os.v1.OsProviderKindR\n" +
	"osProvider\x12,\n" +
	"\x0fplatform_bundle\x18\x0f \x01(\tB\x03\xe0A\x03R\x0eplatformBundle\x12H\n" +
	"\bmetadata\x18\x12 \x01(\tB,\xbaH)r'\x18\xf4\x032\"^$|^[a-z0-9,.\\-_:/\"\\\\ \\\\n{}\\[\\]]+$R\bmetadata\x12o\n" +
	"\vtls_ca_cert\x18\x13 \x01(\tBO\xbaHLrJ\x10\x00\x18\x90N2C^$|^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$R\ttlsCaCert\x12:\n" +
	"\x11existing_cves_url\x18* \x01(\tB\x0e\xe0A\x05\xbaH\br\x06\x18\xf4\x03\x90\x01\x01R\x0fexistingCvesUrl\x12k\n" +
	"\rexisting_cves\x18+ \x01(\tBF\xe0A\x03\xbaH@r>\x18\xa0\xc2\x1e28^$|^[a-zA-Z-_0-9./:;=@?!#,<>*+~()\"\\\\À-ÿ \\\\n\\{\\}\\[\\]]+$R\fexistingCves\x124\n" +
	"\x0efixed_cves_url\x18, \x01(\tB\x0e\xe0A\x05\xbaH\br\x06\x18\xf4\x03\x90\x01\x01R\ffixedCvesUrl\x12X\n" +
	"\n" +
	"fixed_cves\x18- \x01(\tB9\xe0A\x03\xbaH3r1\x18\xa0\xc2\x1e2+^$|^[\\p{L}\\p{N}\\p{P}\\p{S}\\p{Z}\\n\\{\\}\\[\\]]+$R\tfixedCves\x12B\n" +
	"\ros_resourceID\x18\x89' \x01(\tB\x1c\xe0A\x03\xbaH\x16r\x14\x18\v2\x10^os-[0-9a-f]{8}$R\fosResourceID\x12J\n" +
	"\brepo_url\x18\x8a' \x01(\tB.\xbaH+r)\x18\xf4\x032$^$|^[a-zA-Z-_0-9./:;=@?!#,<>*()\" ]+$R\arepoUrl\x12F\n" +
	"\n" +
	"timestamps\x18\xb4\x87\x03 \x01(\v2\x1f.resources.common.v1.TimestampsB\x03\xe0A\x03R\n" +
	"timestampsJ\x04\b\x04\x10\x05J\x04\b\x05\x10\x06*\x89\x01\n" +
	"\x0fSecurityFeature\x12 \n" +
	"\x1cSECURITY_FEATURE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SECURITY_FEATURE_NONE\x10\x01\x129\n" +
	"5SECURITY_FEATURE_SECURE_BOOT_AND_FULL_DISK_ENCRYPTION\x10\x02*M\n" +
	"\x06OsType\x12\x17\n" +
	"\x13OS_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fOS_TYPE_MUTABLE\x10\x01\x12\x15\n" +
	"\x11OS_TYPE_IMMUTABLE\x10\x02*k\n" +
	"\x0eOsProviderKind\x12 \n" +
	"\x1cOS_PROVIDER_KIND_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16OS_PROVIDER_KIND_INFRA\x10\x01\x12\x1b\n" +
	"\x17OS_PROVIDER_KIND_LENOVO\x10\x02BWZUgithub.com/open-edge-platform/infra-core/apiv2/v2/internal/pbapi/resources/os/v1;osv1b\x06proto3"

var (
	file_resources_os_v1_os_proto_rawDescOnce sync.Once
	file_resources_os_v1_os_proto_rawDescData []byte
)

func file_resources_os_v1_os_proto_rawDescGZIP() []byte {
	file_resources_os_v1_os_proto_rawDescOnce.Do(func() {
		file_resources_os_v1_os_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resources_os_v1_os_proto_rawDesc), len(file_resources_os_v1_os_proto_rawDesc)))
	})
	return file_resources_os_v1_os_proto_rawDescData
}

var file_resources_os_v1_os_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_resources_os_v1_os_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_resources_os_v1_os_proto_goTypes = []any{
	(SecurityFeature)(0),            // 0: resources.os.v1.SecurityFeature
	(OsType)(0),                     // 1: resources.os.v1.OsType
	(OsProviderKind)(0),             // 2: resources.os.v1.OsProviderKind
	(*OperatingSystemResource)(nil), // 3: resources.os.v1.OperatingSystemResource
	(*v1.Timestamps)(nil),           // 4: resources.common.v1.Timestamps
}
var file_resources_os_v1_os_proto_depIdxs = []int32{
	0, // 0: resources.os.v1.OperatingSystemResource.security_feature:type_name -> resources.os.v1.SecurityFeature
	1, // 1: resources.os.v1.OperatingSystemResource.os_type:type_name -> resources.os.v1.OsType
	2, // 2: resources.os.v1.OperatingSystemResource.os_provider:type_name -> resources.os.v1.OsProviderKind
	4, // 3: resources.os.v1.OperatingSystemResource.timestamps:type_name -> resources.common.v1.Timestamps
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_resources_os_v1_os_proto_init() }
func file_resources_os_v1_os_proto_init() {
	if File_resources_os_v1_os_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resources_os_v1_os_proto_rawDesc), len(file_resources_os_v1_os_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_resources_os_v1_os_proto_goTypes,
		DependencyIndexes: file_resources_os_v1_os_proto_depIdxs,
		EnumInfos:         file_resources_os_v1_os_proto_enumTypes,
		MessageInfos:      file_resources_os_v1_os_proto_msgTypes,
	}.Build()
	File_resources_os_v1_os_proto = out.File
	file_resources_os_v1_os_proto_goTypes = nil
	file_resources_os_v1_os_proto_depIdxs = nil
}
